### PR TITLE
StreamLogFiles: Move throw of OverwriteException outside of catch-all

### LINKED ISSUE #273: Apparent regression after PR #263: race in hole fill
This appears to be a regression after the merge of #263. In the parallel version of QuickCheck test for the SMRMap, there's an occasional error where an exception is thrown server-side in a race with a hole fill.  @Maithem, could you take a peek?  This appears to destabilize any concurrent updates to `SMRMap` objects.

The problem is quite non-deterministic, it's much easier to see when using the default logging level.  For detailed trace, reproduce using.

Server:

    % ./bin/corfu_server -Q -l /tmp/some/path -s 8000 --cm-poll-interval=99999 -d TRACE > & foo

Client, which performs random valid API ops from the `SMRMap` API.  All ops are using the same streamID and thus same `SMRMap` object.

    % cd src/test/erlang
    % ./Build.sh proper
    % ./Build.sh proper-shell
    > proper:quickcheck(proper:numtests(2000, map_qc:prop_parallel()), [noshrink]).

... and then wait for a `WARN` level message in the `foo` log file mentioning:

     17:50:21.760 ERROR [event-5] o.c.i.l.StreamLogFiles - Disk_write[0]: Exception
     org.corfudb.runtime.exceptions.OverwriteException: null
            at org.corfudb.infrastructure.log.StreamLogFiles.append(StreamLogFiles.java:208)

Note that this usually happens at log offset 0, but I have seen it happen rarely at other offsets (e.g. 3 or 12).

At standard trace level, the output can look like this:

     17:50:21.524 WARN  [DistErl-8] o.c.i.SequencerServer - Sequencer recovery requested but checkpoint not set, defaulting to 0
     17:50:21.752 INFO  [event-5] o.c.i.l.StreamLogFiles - Opened new log file at /tmp/some/path/log0
     17:50:21.752 INFO  [event-11] o.c.i.l.StreamLogFiles - Disk_write[0]: Written to disk.
     17:50:21.760 ERROR [event-5] o.c.i.l.StreamLogFiles - Disk_write[0]: Exception
     org.corfudb.runtime.exceptions.OverwriteException: null
            at org.corfudb.infrastructure.log.StreamLogFiles.append(StreamLogFiles.java:208)
    17:50:21.761 ERROR [event-5] o.c.i.NettyServerRouter - Exception during read!
     java.lang.RuntimeException: org.corfudb.runtime.exceptions.OverwriteException
            at org.corfudb.infrastructure.log.StreamLogFiles.append(StreamLogFiles.java:213)
    Caused by: org.corfudb.runtime.exceptions.OverwriteException: null
            at org.corfudb.infrastructure.log.StreamLogFiles.append(StreamLogFiles.java:208)
    17:50:21.768 INFO  [event-1] o.c.i.l.StreamLogFiles - Disk_write[1]: Written to disk.
     17:50:21.783 INFO  [event-15] o.c.i.l.StreamLogFiles - Disk_write[2]: Written to disk.
     17:50:26.758 WARN  [DistErl-1] o.c.r.v.AbstractView - Timeout executing remote call, invalidating view and retrying in 5s
     17:50:31.764 ERROR [event-5] o.c.i.l.StreamLogFiles - Disk_write[0]: Exception
     org.corfudb.runtime.exceptions.OverwriteException: null
            at org.corfudb.infrastructure.log.StreamLogFiles.append(StreamLogFiles.java:208)
    17:50:31.764 ERROR [event-5] o.c.i.NettyServerRouter - Exception during read!
     java.lang.RuntimeException: org.corfudb.runtime.exceptions.OverwriteException
            at org.corfudb.infrastructure.log.StreamLogFiles.append(StreamLogFiles.java:213)
    Caused by: org.corfudb.runtime.exceptions.OverwriteException: null
            at org.corfudb.infrastructure.log.StreamLogFiles.append(StreamLogFiles.java:208)
    17:50:33.753 INFO  [event-13] o.c.i.l.StreamLogFiles - Disk_write[3]: Written to disk.

For a `TRACE` level log, see https://gist.github.com/slfritchie/eac869fd354eeda4a1bbc56db995cd57

### PR DESCRIPTION
**Pull request by slfritchie**
StreamLogFiles.append() was throwing an `OverwriteException` inside of a catch-all try block.  Move the throw outside of the catch-all to match original caller's expectation.

I've also patched up the unit tests to expect the shape of the `OverwriteException`.  Reviewer: please double-check.  The execution passes, but a sanity check from someone else would be good, thanks.

Fixes #273.

### CODE REVIEW

File: infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java [hunk 1]
```diff
@@ -290,6 +290,7 @@ private void writeRecord(FileHandle fh, long address, LogData entry) throws IOEx
 
     @Override
     public void append(long address, LogData entry) {
+        int res = 0;
```
Comment (no2chem) [inline infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java]: Why use a int instead of a bool if you intend to represent a bool?

File: infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java [hunk 2]
```diff
@@ -298,15 +299,17 @@ public void append(long address, LogData entry) {
...
                 fh.getKnownAddresses().add(address);
                 writeRecord(fh, address, entry);
-
+                log.info("Disk_write[{}]: Written to disk.", address);
             } else {
-                throw new OverwriteException();
+                res = 1;     // Throw OverwriteException outside of this try/catch block
             }
-            log.info("Disk_write[{}]: Written to disk.", address);
         } catch (Exception e) {
```
Comment (no2chem) [inline infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java]: The only checked exception being thrown in this block is IOException, so catch IOException instead and throw OverwriteException when needed.

**Comment by slfritchie** [comment]
@no2chem Rewritten, mind taking a peek?
