### PR TITLE
Fix QuorumReplicationProtocol

### LINKED ISSUE #1182: Failing test checkRecoveryWriteTriggeredFromReadRecoversDataWhenTheQuorumIsLost
## Overview
Test fails throwing QuorumUnreachableException.

```
mvn -pl test -Dtest=QuorumReplicationProtocolAdditionalTests#checkRecoveryWriteTriggeredFromReadRecoversDataWhenTheQuorumIsLost test
```

```
checkRecoveryWriteTriggeredFromReadRecoversDataWhenTheQuorumIsLost[FAIL - QuorumUnreachableException:L136]
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.763 sec <<< FAILURE! - in org.corfudb.runtime.view.replication.QuorumReplicationProtocolAdditionalTests
checkRecoveryWriteTriggeredFromReadRecoversDataWhenTheQuorumIsLost(org.corfudb.runtime.view.replication.QuorumReplicationProtocolAdditionalTests)  Time elapsed: 0.949 sec  <<< ERROR!
org.corfudb.runtime.exceptions.QuorumUnreachableException: Couldn't reach quorum, reachable=1, required=2
	at org.corfudb.runtime.view.QuorumFuturesFactory$CompositeFuture.get(QuorumFuturesFactory.java:200)
	at org.corfudb.runtime.view.QuorumFuturesFactory$CompositeFuture.get(QuorumFuturesFactory.java:221)
	at org.corfudb.util.CFUtils.getUninterruptibly(CFUtils.java:41)
	at org.corfudb.util.CFUtils.getUninterruptibly(CFUtils.java:86)
	at org.corfudb.runtime.view.replication.QuorumReplicationProtocol.peek(QuorumReplicationProtocol.java:81)
	at org.corfudb.runtime.view.replication.AbstractReplicationProtocol.lambda$read$0(AbstractReplicationProtocol.java:42)
	at org.corfudb.runtime.view.replication.ReadWaitHoleFillPolicy.peekUntilHoleFillRequired(ReadWaitHoleFillPolicy.java:50)
	at org.corfudb.runtime.view.replication.AbstractReplicationProtocol.read(AbstractReplicationProtocol.java:41)
	at org.corfudb.runtime.view.AddressSpaceView.lambda$fetch$25(AddressSpaceView.java:385)
	at org.corfudb.runtime.view.AbstractView.layoutHelper(AbstractView.java:89)
	at org.corfudb.runtime.view.AbstractView.layoutHelper(AbstractView.java:59)
	at org.corfudb.runtime.view.AddressSpaceView.fetch(AddressSpaceView.java:383)
	at org.corfudb.runtime.view.AddressSpaceView.read(AddressSpaceView.java:198)
	at org.corfudb.runtime.view.replication.QuorumReplicationProtocolAdditionalTests.checkRecoveryWriteTriggeredFromReadRecoversDataWhenTheQuorumIsLost(QuorumReplicationProtocolAdditionalTests.java:136)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.corfudb.AbstractCorfuTest$1$1.evaluate(AbstractCorfuTest.java:76)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)


Results :

Tests in error:
  QuorumReplicationProtocolAdditionalTests.checkRecoveryWriteTriggeredFromReadRecoversDataWhenTheQuorumIsLost:136 » QuorumUnreachable
```

### PR DESCRIPTION
**Pull request by zalokhan**
## Overview

Description:
Peek should return null when encountering QuorumUnreachableException.

Why should this be merged: 
Fixes test: checkRecoveryWriteTriggeredFromReadRecoversDataWhenTheQuorumIsLost
Re-adding catch block from intermediate change #1082 

Related issue(s) (if applicable): Fixes #1182 

## Checklist (Definition of Done):

- [x] There are no TODOs left in the code
- [x] [Coding conventions](https://github.com/CorfuDB/CorfuDB/wiki/Corfu-Style-Guidelines) (e.g. for logging, unit tests) have been followed
- [x] Change is covered by automated tests
- [x] Public API has Javadoc

### CODE REVIEW

File: runtime/src/main/java/org/corfudb/runtime/view/replication/QuorumReplicationProtocol.java [hunk 1]
```diff
@@ -71,14 +71,19 @@ public ILogData peek(Layout layout, long address) {
...
+                CompletableFuture<ReadResponse>[] futures = new CompletableFuture[numUnits];
+                for (int i = 0; i < numUnits; i++) {
+                    futures[i] = layout.getLogUnitClient(address, i).read(address);
+                }
+                QuorumFuturesFactory.CompositeFuture<ReadResponse> future =
+                        QuorumFuturesFactory.getQuorumFuture(new ReadResponseComparator(address),
+                                futures);
+                readResponse = CFUtils.getUninterruptibly(future, QuorumUnreachableException.class);
+            } catch (QuorumUnreachableException e) {
+                log.debug(e.getMessage(), e);
```
Comment (no2chem) [inline runtime/src/main/java/org/corfudb/runtime/view/replication/QuorumReplicationProtocol.java]: Can you add some description here? "peek: Quorum unreachable: {}"

Comment (zalokhan) [reply runtime/src/main/java/org/corfudb/runtime/view/replication/QuorumReplicationProtocol.java]: Sure. Done.
