### PR TITLE
Chain min replication factor set to 1.

### LINKED ISSUE #1325: Chain replication minimum factor 2 causes deadlock.
## Overview
Consider the following scenario with 3 nodes A, B and C using chain replication A -> B -> C.
The cluster is bootstrapped with the following layout:
```
Epoch:0
Segments: [0 to -1: A->B->C]
```
Node B fails causing B to be marked unresponsive and removed from the chain
```
Epoch:1
Segments: [0 to -1: A->C]
Unresponsive: B
```
Now Node B recovers. The healing workflow kicks in splitting the segment at address 10 to add node B.
```
Epoch:2
Segments: [0 to 10: A->C], [10 to -1: A->C->B]
```
The next step would be to restore redundacy in node B for the first segment.
However, before this can be done, node C crashes.
This creates a deadlock as node B cannot recover as it cannot read the first segment from the tail of the chain (Node C). At the same time, Node C cannot be removed from the chain as it violates the minimum replication factor.

### PR DESCRIPTION
**Pull request by zalokhan**
## Overview
Description: Change the min replication factor for Chain replication to 1.
Also corrects the Quorum replication min factor to calculate the quorum based on log servers in each stripe.

Why should this be merged: Resolves liveness issue caused by #1325

Related issue(s) (if applicable): Resolves #1325 and #1322 

## Checklist (Definition of Done):

- [x] There are no TODOs left in the code
- [x] [Coding conventions](https://github.com/CorfuDB/CorfuDB/wiki/Corfu-Style-Guidelines) (e.g. for logging, unit tests) have been followed
- [x] Change is covered by automated tests
- [x] Public API has Javadoc

### CODE REVIEW

File: test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java [hunk 1]
```diff
@@ -1500,11 +1501,13 @@ public void queryClusterStatus() throws Exception {
...
+                        return true;
                     }
-                    return true;
-                }));
+                    return false;
+                }).drop());
         addServerRule(SERVERS.PORT_1, new TestRule().drop().always());
-        latch.tryAcquire(PARAMETERS.TIMEOUT_NORMAL.toMillis(), TimeUnit.MILLISECONDS);
+        getManagementServer(SERVERS.PORT_1).shutdown();
+        latch.acquire();
```
Comment (Maithem) [inline test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java]: I think this should be time bounded.

Comment (zalokhan) [reply test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java]: Right, I'll put the tryAcquire back.

File: runtime/src/main/java/org/corfudb/runtime/view/Layout.java [hunk 2]
```diff
@@ -452,7 +452,7 @@ public abstract void validateSegmentSeal(LayoutSegment layoutSegment,
          * @param layout the layout to compute the min replication factor for
```
Comment (StrikingThirteen) [inline runtime/src/main/java/org/corfudb/runtime/view/Layout.java]: can we have the stripe added to comments too?

File: runtime/src/main/java/org/corfudb/runtime/view/Layout.java [hunk 3]
```diff
@@ -329,8 +329,8 @@ public void validateSegmentSeal(LayoutSegment layoutSegment,
             }
 
             @Override
-            public int getMinReplicationFactor(Layout layout) {
-                return 2;
+            public int getMinReplicationFactor(Layout layout, LayoutStripe stripe) {
```
Comment (annym) [inline runtime/src/main/java/org/corfudb/runtime/view/Layout.java]: This might be a bit unrelated, but why isn't the LayoutStripe part of the Layout definition?

File: runtime/src/main/java/org/corfudb/runtime/view/Layout.java [hunk 4]
```diff
@@ -329,8 +329,8 @@ public void validateSegmentSeal(LayoutSegment layoutSegment,
...
+                return 1;
```
Comment (annym) [inline runtime/src/main/java/org/corfudb/runtime/view/Layout.java]: Would it make somehow sense for the replication factor to be defined/changed in the layout file? so it is not actually hard coded, and default to this if not present?

File: runtime/src/main/java/org/corfudb/runtime/view/Layout.java (hunk 3 above)
Comment (zalokhan) [reply runtime/src/main/java/org/corfudb/runtime/view/Layout.java]: Layout stripe is a part of the layout. We can just pass the stripe index and infer the stripe from the passed layout object. I felt this would be more intuitive since we already have the stripe.

File: runtime/src/main/java/org/corfudb/runtime/view/Layout.java (hunk 4 above)
Comment (zalokhan) [reply runtime/src/main/java/org/corfudb/runtime/view/Layout.java]: The minimum replication factor should not change that often for it to be configurable. We hit a deadlock condition if the minimum replication factor is 2 in case of Chain replication.
On the other hand, the minimum replication factor would not be constant for quorum replication. It would increase as the number of nodes in the stripe increase and decrease when the nodes are removed.

File: runtime/src/main/java/org/corfudb/runtime/view/Layout.java (hunk 3 above)
Comment (annym) [reply runtime/src/main/java/org/corfudb/runtime/view/Layout.java]: Ok, I see I was a bit confused because both were passed separately. But then I agree passing the stripe is more intuitive than the stripe index.

File: runtime/src/main/java/org/corfudb/runtime/view/Layout.java (hunk 4 above)
Comment (annym) [reply runtime/src/main/java/org/corfudb/runtime/view/Layout.java]: Ok, I was only thinking it for the chain replication but if this leads to potential deadlock then it would make sense to leave it out of the scope of the layout. 

Just to be sure, stripes are updated as a server becomes unresponsive? I'm just trying to make sure that stripes are not accounting for log servers that are down.

Comment (zalokhan) [reply runtime/src/main/java/org/corfudb/runtime/view/Layout.java]: Yes, the stripes are updated. If a node is down it is removed from the stripe. Provided the number of nodes remaining in the stripe is greater than or equal to the `minReplicationFactor`.
If not, the system just hangs until the condition is satisfied.

**Comment by zalokhan** [comment]
@Maithem @StrikingThirteen I have addressed your comments.
