### PR TITLE
Transfer delta in state transfer.

### LINKED ISSUE #1910: Add node fails if partial state transfer fails.
## Overview

These are the following events:
- The first Join is successful.
- The second join starts:
- The Orchestrator starts syncing the data to the newly joined node.
- State transfer continues in chunks of 10 addresses until a certain chunk which is too large:

Thread-8 |  o.c.i.o.actions.StateTransfer | stateTransfer: read 24655-24754 in 6 ms
Thread-8 |  o.c.i.o.actions.StateTransfer | stateTransfer: Transferred address chunk [24655, 24754] to 10.172.177.55:9000 in 170 ms

Large chunk. The read takes 4.7 secs. The Corfu timeout is 5 secs.
Thread-8 |  o.c.i.o.actions.StateTransfer | stateTransfer: read 24755-24854 in 4739 ms

The write timesout on the client side.
Thread-8 |      o.c.i.orchestrator.Action | execute: Error executing action RestoreRedundancy on retry 0. Invalidating layout.
java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException
However, the data was written on the server.
We fail on attempting to re-write this chunk with an overwrite exception.
The Orchestrator needs to check if the data to be copied is the same and ignore the overwrite exception.

We do not see this in Heal Node workflow as it wipes out the data before retrying.

### PR DESCRIPTION
**Pull request by zalokhan**
## Overview

Description:
Transfer delta in state transfer.

Why should this be merged: 
If transfer range overlaps with previous transfer, overwrite exceptions are thrown and state transfer fails.

Related issue(s) (if applicable): Fixes #1910 

## Checklist (Definition of Done):

- [x] There are no TODOs left in the code
- [x] [Coding conventions](https://github.com/CorfuDB/CorfuDB/wiki/Corfu-Style-Guidelines) (e.g. for logging, unit tests) have been followed
- [x] Change is covered by automated tests
- [x] Public API has Javadoc

### CODE REVIEW

File: test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java [hunk 1]
```diff
@@ -1499,6 +1501,113 @@ public void verifyStateTransferNotHappenButMergeSucceeds() throws Exception {
...
+                    .addToLayout()
+                    .build();
+            bootstrapAllServers(layout);
+
+            corfuRuntime = getNewRuntime(getDefaultNode()).connect();
+
+            setAggressiveTimeouts(layout, corfuRuntime);
+
+            IStreamView testStream = corfuRuntime.getStreamsView().get(CorfuRuntime.getStreamID("test"));
+            // Write to address spaces 0 to 11_000 (inclusive) to SERVER 0 only.
```
Comment (hisundar) [inline test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java]: nit: Write to address spaces 0 to 11_000 (inclusive) go to SERVER 0 only.

File: test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java [hunk 2]
```diff
@@ -1499,6 +1501,113 @@ public void verifyStateTransferNotHappenButMergeSucceeds() throws Exception {
...
+            // Write to address spaces 11_000 to 12_000 (inclusive) to SERVERS 0 & 1.
```
Comment (hisundar) [inline test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java]: nit:Write to address spaces 11_000 to 12_000 (inclusive) go to SERVERS 0 & 1.
?

File: infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/StateTransfer.java [hunk 3]
```diff
@@ -26,6 +25,8 @@
 @Slf4j
 public class StateTransfer {
 
+    private static final int RECORDS_PER_LOG_FILE = 10_000;
```
[the remark this answers is not in the document]
Comment (zalokhan) [reply infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/StateTransfer.java]: Yes, I tried that. 
It has to be the other way round as runtime does not have any dependency on infrastructure.

[the remark this answers is not in the document]
Comment (zalokhan) [reply infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/StateTransfer.java]: Sorry, my bad. The class is under infrastructure and I can import the field directly. Will do that. Thanks.

**Comment by zalokhan** [comment]
If 2 state transfer jobs are running in parallel, both of them will preempt each other since they both try to transfer the addresses not present at the destination.
I am adding an exponential backoff mechanism to this in case of an overwrite exception.

File: infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/StateTransfer.java [hunk 4]
```diff
@@ -30,96 +39,206 @@ private StateTransfer() {
...
-                                Set<String> endpoints,
+                                @NonNull String endpoint,
                                 CorfuRuntime runtime,
-                                Layout.LayoutSegment segment) throws ExecutionException, InterruptedException {
+                                Layout.LayoutSegment segment) throws Exception {
 
-        if (endpoints.isEmpty()) {
-            log.debug("stateTransfer: No server needs to transfer for segment [{} - {}], " +
-                    "skipping state transfer for this segment.", segment.getStart(), segment.getEnd());
+        if (endpoint.isEmpty()) {
```
Comment (WenbinZhu) [inline infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/StateTransfer.java]: This block should be removed as endpoints is no longer a `Set`.

File: infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/RestoreRedundancyMergeSegments.java [hunk 5]
```diff
@@ -64,7 +60,9 @@ public void impl(@Nonnull CorfuRuntime runtime) throws OutrankedException,
             // Currently the state is transferred for the complete segment.
             // TODO: Add stripe specific transfer granularity for optimization.
             // Transfer the replicated segment to the difference set calculated above.
-            StateTransfer.transfer(layout, lowRedundancyServers, runtime, layout.getFirstSegment());
+            for (String lowRedundancyServer : lowRedundancyServers) {
```
Comment (WenbinZhu) [inline infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/RestoreRedundancyMergeSegments.java]: This whole merge logic assumes no more than two segments exists. It inspects the first two segments, do transfer, but merge the last two segment, which is wrong if there are multiple segments (could happen). This wrong logic has been there for a while, can we fix it this time?

File: infrastructure/src/main/java/org/corfudb/infrastructure/ServerContext.java [hunk 6]
```diff
@@ -89,6 +89,8 @@
     /** The node Id, stored as a base64 string. */
     private static final String NODE_ID = "NODE_ID";
 
+    public static final int RECORDS_PER_LOG_FILE = 10_000;
```
Comment (Maithem) [inline infrastructure/src/main/java/org/corfudb/infrastructure/ServerContext.java]: The way the LogUnit partitions its data is implementation detail and its not meant to be exposed.

File: infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLog.java [hunk 7]
```diff
@@ -77,6 +79,15 @@
...
 
+    /**
+     * Returns the missing addresses in this Log Unit in the specified consecutive
+     * range of addresses. The range cannot be larger than RECORDS_PER_LOG_FILE.
+     *
+     * @param range Range of addresses to compare.
+     * @return Set of missing addresses.
+     */
+    Set<Long> getMissingAddresses(Range<Long> range);
+
```
Comment (Maithem) [inline infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLog.java]: I think this is more appropriate `List<Long> queryAddressesInRange(long lowerEndpoint, UpperEndpoint)`

Also, since the request size is not validated, I don't feel like it makes sense to mention RECORDS_PER_LOG_FILE. I think this limit should be set by the client anyways.

File: infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java [hunk 8]
```diff
@@ -1012,6 +1018,35 @@ private boolean verify(List<LogData> range) {
...
 
+    /**
+     * This method requests for missing addresses in this Log Unit in the specified consecutive
+     * range of addresses. The range cannot be larger than RECORDS_PER_LOG_FILE.
+     *
+     * @param range Range of addresses to compare.
+     * @return Set of missing addresses.
+     */
+    @Override
+    public Set<Long> getMissingAddresses(Range<Long> range) {
```
Comment (Maithem) [inline infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java]: please simplify

```java

    public List<Long> rangeQuery(Range<Long> range) {
        List<Long> ret = new ArrayList<>(1000);
        for (long a = range.lowerEndpoint(); a <= range.upperEndpoint(); a++) {
            if (getSegmentHandleForAddress(a).getKnownAddresses().containsKey(a)) {
                ret.add(a);
            }
        }
        return ret;
    }
```

File: infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/StateTransfer.java [hunk 9]
```diff
@@ -30,96 +39,206 @@ private StateTransfer() {
...
+            log.debug("stateTransfer: No server needs to transfer for segment [{} - {}], "
+                            + "skipping state transfer for this segment.",
+                    segment.getStart(), segment.getEnd());
             return;
         }
 
-        int batchSize = runtime.getParameters().getBulkReadSize();
+        int chunkSize = runtime.getParameters().getBulkReadSize();
+        final AtomicInteger overwriteRetries = new AtomicInteger();
```
Comment (Maithem) [inline infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/StateTransfer.java]: Why is this an AtomicInteger ?

File: infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/StateTransfer.java (hunk 4 above)
Comment (Maithem) [reply infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/StateTransfer.java]: Also, why call transfer, if the caller can just not call it?

Comment (zalokhan) [reply infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/StateTransfer.java]: @WenbinZhu Removed the call.
@Maithem The layout could have changed on a retry which causes the segments to have merged.
Fixed.

File: infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/StateTransfer.java [hunk 10]
```diff
@@ -30,96 +39,206 @@ private StateTransfer() {
...
+                                @NonNull String endpoint,
                                 CorfuRuntime runtime,
-                                Layout.LayoutSegment segment) throws ExecutionException, InterruptedException {
+                                Layout.LayoutSegment segment) throws Exception {
 
-        if (endpoints.isEmpty()) {
-            log.debug("stateTransfer: No server needs to transfer for segment [{} - {}], " +
-                    "skipping state transfer for this segment.", segment.getStart(), segment.getEnd());
+        if (endpoint.isEmpty()) {
+            log.debug("stateTransfer: No server needs to transfer for segment [{} - {}], "
```
Comment (annym) [inline infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/StateTransfer.java]: Also this message should change right, as it is not all servers.

File: infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/StateTransfer.java [hunk 11]
```diff
@@ -30,96 +39,206 @@ private StateTransfer() {
...
+                if (trimMark > segment.getEnd()) {
+                    log.info("stateTransfer: Nothing to transfer, trimMark {}"
+                                    + "greater than end of segment {}",
+                            trimMark, segment.getEnd());
+                    return true;
+                }
 
-            long ts2 = System.currentTimeMillis();
+                // State transfer should start from segment start address or trim mark
+                // whichever is lower.
```
Comment (annym) [inline infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/StateTransfer.java]: lower or higher?

File: infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/RestoreRedundancyMergeSegments.java (hunk 5 above)
Comment (zalokhan) [reply infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/RestoreRedundancyMergeSegments.java]: That's not true. That would have been a serious data loss issue.
We merge only the segment which we transfer.
Let's discuss this offline if I am not understanding this right.

File: infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/StateTransfer.java [hunk 12]
```diff
@@ -30,96 +39,206 @@ private StateTransfer() {
...
+                final long segmentStart = Math.max(trimMark, segment.getStart());
```
Comment (annym) [inline infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/StateTransfer.java]: couldn't the trim mark be out of this segment? in which case it does not correspond to the given segment end?

File: test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java [hunk 13]
```diff
@@ -1499,6 +1501,113 @@ public void verifyStateTransferNotHappenButMergeSucceeds() throws Exception {
         waitForLayoutChange(l -> l.getSegments().size() == 1, rt);
     }
 
+    /**
```
Comment (annym) [inline test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java]: Could we add a test for competing state transfers? that certainly they do not block each other.

File: infrastructure/src/main/java/org/corfudb/infrastructure/ServerContext.java (hunk 6 above)
Comment (zalokhan) [reply infrastructure/src/main/java/org/corfudb/infrastructure/ServerContext.java]: Will make it another configuration parameter.

File: infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/StateTransfer.java (hunk 9 above)
Comment (zalokhan) [reply infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/StateTransfer.java]: It's used in the lambda which requires a final variable.

File: infrastructure/src/main/java/org/corfudb/infrastructure/ServerContext.java (hunk 6 above)
[the remark this answers is not in the document]
Comment (zalokhan) [reply infrastructure/src/main/java/org/corfudb/infrastructure/ServerContext.java]: No, these should not be linked. I have reverted this change.
The StreamLogFiles will have its `RECORDS_PER_LOG_FILE` and the State transfer will use its own parameter.

File: infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java [hunk 14]
```diff
@@ -321,6 +333,22 @@ private void multiRead(CorfuPayloadMsg<MultipleReadRequest> msg, ChannelHandlerC
         }
     }
 
+    /**
+     * Handles requests for missing entries in specified range.
+     * This is used by state transfer to catchup only the remainder of the segment.
```
[the remark this answers is not in the document]
Comment (zalokhan) [reply infrastructure/src/main/java/org/corfudb/infrastructure/LogUnitServer.java]: Fixed.

File: infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java (hunk 8 above)
Comment (zalokhan) [reply infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java]: This would acquire a lock, every time you call `getSegmentHandleForAddress`.
I can work on simplifying this.

File: infrastructure/src/main/java/org/corfudb/infrastructure/BatchProcessor.java [hunk 15]
```diff
@@ -184,6 +187,15 @@ private void processor() {
                                 // Retrieve the address space for every stream in the log.
                                 currOp.setResultValue(streamLog.getStreamsAddressSpace());
                                 break;
+                            case MISSING_ADDRESSES_IN_RANGE:
```
Comment (Maithem) [inline infrastructure/src/main/java/org/corfudb/infrastructure/BatchProcessor.java]: This doesn't have to be part of the batch writer, please remove it.

File: runtime/src/main/java/org/corfudb/protocols/wireprotocol/MissingAddressResponse.java [hunk 16]
```diff
@@ -0,0 +1,33 @@
...
+
+/**
+ * Response for missing addresses in the log unit server for a specified range.
+ * Created by zlokhandwala on 2019-06-01.
+ */
+@Data
+@AllArgsConstructor
+public class MissingAddressResponse implements ICorfuPayload<MissingAddressResponse> {
+
+    private final Set<Long> missingAddresses;
```
[the remark this answers is not in the document]
Comment (zalokhan) [reply runtime/src/main/java/org/corfudb/protocols/wireprotocol/MissingAddressResponse.java]: The payload is not that large. So I haven't considered this.
10,000 addresses will correspond to 80Kbytes.

File: infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java (hunk 8 above)
Comment (zalokhan) [reply infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java]: Done.

File: infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLog.java (hunk 7 above)
Comment (zalokhan) [reply infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLog.java]: Done.

File: infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java [hunk 17]
```diff
@@ -1012,6 +1018,35 @@ private boolean verify(List<LogData> range) {
...
+
+        if (range.upperEndpoint() - range.lowerEndpoint() > RECORDS_PER_LOG_FILE) {
+            String msg = String.format("Range too large: [%d-%d]. Number of addresses: %d",
+                    range.lowerEndpoint(), range.upperEndpoint(),
+                    (range.upperEndpoint() - range.lowerEndpoint()));
+            throw new IllegalArgumentException(msg);
+        }
+
+        SegmentHandle firstSh = getSegmentHandleForAddress(range.lowerEndpoint());
```
[the remark this answers is not in the document]
Comment (zalokhan) [reply infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java]: They could. I changed the implementation.

File: infrastructure/src/main/java/org/corfudb/infrastructure/BatchProcessor.java (hunk 15 above)
Comment (zalokhan) [reply infrastructure/src/main/java/org/corfudb/infrastructure/BatchProcessor.java]: Fixed.

File: infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/StateTransfer.java (hunk 11 above)
Comment (zalokhan) [reply infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/StateTransfer.java]: higher. Fixed.

File: infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/StateTransfer.java (hunk 10 above)
Comment (zalokhan) [reply infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/StateTransfer.java]: Fixed this.

File: infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/StateTransfer.java (hunk 12 above)
Comment (zalokhan) [reply infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/StateTransfer.java]: In that case, there is nothing to transfer.

File: infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java [hunk 18]
```diff
@@ -1012,6 +1017,26 @@ private boolean verify(List<LogData> range) {
...
+     * range of addresses.
+     *
+     * @param range Range of addresses to compare.
+     * @return List of missing addresses.
+     */
+    @Override
+    public List<Long> getMissingAddresses(Range<Long> range) {
+
+        List<Long> result = new ArrayList<>(10_000);
+        for (long address = range.lowerEndpoint(); address <= range.upperEndpoint(); address++) {
```
Comment (Maithem) [inline infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java]: I think the converse is more natural. Given a set, we have contains method and not doesntContain.

File: infrastructure/src/main/java/org/corfudb/infrastructure/log/InMemoryStreamLog.java [hunk 19]
```diff
@@ -121,6 +126,20 @@ private void throwLogUnitExceptionsIfNecessary(long address, LogData entry) {
...
 
+    /**
+     * Returns the missing addresses in this Log Unit in the specified consecutive
+     * range of addresses.
+     *
+     * @param range Range of addresses to compare.
+     * @return Set of missing addresses.
+     */
+    @Override
+    public Set<Long> getMissingAddresses(Range<Long> range) {
```
[the remark this answers is not in the document]
Comment (zalokhan) [reply infrastructure/src/main/java/org/corfudb/infrastructure/log/InMemoryStreamLog.java]: Changed this. Removed the limit now.
The range is specified by the client. A bigger range could lead to longer processing times on the server and thus should be considered while setting the parameter.

File: test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java [hunk 20]
```diff
@@ -1499,6 +1501,113 @@ public void verifyStateTransferNotHappenButMergeSucceeds() throws Exception {
...
+                    .setEnd(writtenAddressesBatch1)
+                    .buildStripe()
+                    .addLogUnit(SERVERS.PORT_0)
+                    .addToSegment()
+                    .addToLayout()
+                    .buildSegment()
+                    .setStart(writtenAddressesBatch1)
+                    .setEnd(-1)
+                    .buildStripe()
+                    .addLogUnit(SERVERS.PORT_0)
```
Comment (epalta) [inline test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java]: Already did addLogUnit(SERVERS.PORT_0) at line 1546

File: test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java [hunk 21]
```diff
@@ -1499,6 +1501,113 @@ public void verifyStateTransferNotHappenButMergeSucceeds() throws Exception {
...
+                    .addSequencer(SERVERS.PORT_0)
+                    .addSequencer(SERVERS.PORT_1)
+                    .buildSegment()
+                    .setStart(0L)
+                    .setEnd(writtenAddressesBatch1)
+                    .buildStripe()
+                    .addLogUnit(SERVERS.PORT_0)
+                    .addToSegment()
+                    .addToLayout()
+                    .buildSegment()
```
Comment (epalta) [inline test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java]: Dup of line 1542

File: test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java (hunk 20 above)
Comment (zalokhan) [reply test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java]: These are 2 different segments which are being created.
Your layout needs to look like this:
```
{
  "layoutServers": [
    "localhost:9000",
    "localhost:9001"
  ],
  "sequencers": [
    "localhost:9000",
    "localhost:9001"
  ],
  "segments": [
    {
      "replicationMode": "CHAIN_REPLICATION",
      "start": 0,
      "end": 11000,
      "stripes": [
        {
          "logServers": [
            "localhost:9000"
          ]
        }
      ]
    },
    {
      "replicationMode": "CHAIN_REPLICATION",
      "start": 11000,
      "end": -1,
      "stripes": [
        {
          "logServers": [
            "localhost:9000",
            "localhost:9001"
          ]
        }
      ]
    }
  ],
  "epoch": 1
}
```

File: test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java (hunk 21 above)
Comment (zalokhan) [reply test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java]: Please see the other comment. This is the layout builder and both these statements are required.

File: test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java (hunk 13 above)
Comment (zalokhan) [reply test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java]: Done.

File: infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/StateTransfer.java [hunk 22]
```diff
@@ -30,96 +38,199 @@ private StateTransfer() {
...
+     * @param endpoint destination node
+     * @param runtime  The runtime to read the segment from
+     * @param segment  segment to transfer
      */
     public static void transfer(Layout layout,
-                                Set<String> endpoints,
+                                @NonNull String endpoint,
                                 CorfuRuntime runtime,
-                                Layout.LayoutSegment segment) throws ExecutionException, InterruptedException {
+                                Layout.LayoutSegment segment) throws Exception {
```
[the remark this answers is not in the document]
Comment (zalokhan) [reply infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/StateTransfer.java]: Done.

File: test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java [hunk 23]
```diff
@@ -1499,6 +1501,113 @@ public void verifyStateTransferNotHappenButMergeSucceeds() throws Exception {
         waitForLayoutChange(l -> l.getSegments().size() == 1, rt);
     }
 
+    /**
+     * This test verifies that partial state transfers when retried only transfer the delta
+     * of the address space.
+     * Setup: Layout - Write 11_000 entries to SERVER 0 and 1_000 entries to SERVERS 0 & 1.
+     * We then trigger the state transfer and force the transfer to fail on the last range write.
+     * Another transfer is then triggered and verified that only the remaining data is transferred.
+     */
```
[the remark this answers is not in the document]
Comment (zalokhan) [reply test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java]: Done.

File: infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/StateTransfer.java [hunk 24]
```diff
@@ -30,96 +38,204 @@ private StateTransfer() {
...
+                        transferChunk(layout, runtime, endpoint, chunk);
+                    }
+                }
+            } catch (OverwriteException oe) {
 
-        for (long chunkStart = segmentStart; chunkStart < segment.getEnd()
-                ; chunkStart = chunkStart + batchSize) {
-            long chunkEnd = Math.min((chunkStart + batchSize - 1), segment.getEnd() - 1);
+                // If Overwrite Exception is due to Different Data, log the error and abort.
+                if (!oe.getOverWriteCause().equals(OverwriteCause.SAME_DATA)) {
```
Comment (Maithem) [inline infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/StateTransfer.java]: This doesn't do what it seems like its doing. Look here #1931

Also, even if `OverwriteCause.SAME_DATA` does a byte-wise comparison its not sufficient because two different writes can skip each others writes without even observing the `OverwriteException`. If you really want to be paranoid then multiple writes should be reading each other's writes and verifying them against theirs.

Comment (zalokhan) [reply infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/StateTransfer.java]: Done.

File: infrastructure/src/main/java/org/corfudb/infrastructure/log/InMemoryStreamLog.java [hunk 25]
```diff
@@ -124,6 +125,25 @@ private void throwLogUnitExceptionsIfNecessary(long address, LogData entry) {
...
 
+    /**
+     * Returns the known addresses in this Log Unit in the specified consecutive
+     * range of addresses.
+     *
+     * @param range Range of addresses to compare.
+     * @return Set of known addresses.
+     */
+    @Override
+    public Set<Long> getKnownAddressesInRange(Range<Long> range) {
```
Comment (Maithem) [inline infrastructure/src/main/java/org/corfudb/infrastructure/log/InMemoryStreamLog.java]: This API is actually not very clear, because the Range can be any combination of open/close endpoints, but the for loop on like 139 assumes that the range is closed/closed. Essentially making an assumption about a generic. For example, [1,2,3) would can return 1,2 and 3, but based on the interface it should return 1 and 2

Comment (Maithem) [reply infrastructure/src/main/java/org/corfudb/infrastructure/log/InMemoryStreamLog.java]: Maybe just use the endpoints directly, no need to wrap them in a Range ?

File: infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java [hunk 26]
```diff
@@ -1021,6 +1022,25 @@ private boolean verify(List<LogData> range) {
...
+    /**
+     * This method requests for known addresses in this Log Unit in the specified consecutive
+     * range of addresses.
+     *
+     * @param range Range of addresses to compare.
+     * @return Set of known addresses.
+     */
+    @Override
+    public Set<Long> getKnownAddressesInRange(Range<Long> range) {
+
```
Comment (Maithem) [inline infrastructure/src/main/java/org/corfudb/infrastructure/log/StreamLogFiles.java]: See comments above.

File: infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/StateTransfer.java [hunk 27]
```diff
@@ -30,96 +33,197 @@ private StateTransfer() {
...
+                        ; chunkStart += chunkSize) {
 
-            long ts2 = System.currentTimeMillis();
+                    long chunkEnd = Math.min(segmentEnd, chunkStart + chunkSize - 1);
 
-            log.info("stateTransfer: read {}-{} in {} ms", chunkStart, chunkEnd, (ts2 - ts1));
+                    // Fetch all missing entries in this range [chunkStart - chunkEnd].
+                    List<Long> chunk = getMissingEntriesChunk(layout, runtime, endpoint,
+                            chunkStart, chunkEnd);
+                    if (chunk.isEmpty()) {
```
Comment (Maithem) [inline infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/StateTransfer.java]: Please log that chunk is being omitted because the orchestrator didn't detect it as missing

File: infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/StateTransfer.java [hunk 28]
```diff
@@ -30,96 +33,197 @@ private StateTransfer() {
...
-            for (long x = chunkStart; x <= chunkEnd; x++) {
-                if (!dataMap.containsKey(x)) {
-                    log.error("Missing address {} in range {}-{}", x, chunkStart, chunkEnd);
-                    throw new IllegalStateException("Missing address");
+                    // Read and write in chunks of chunkSize.
+                    transferChunk(layout, runtime, endpoint, chunk);
                 }
-                entries.add((LogData) dataMap.get(x));
-            }
+            } catch (OverwriteException oe) {
```
Comment (Maithem) [inline infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/StateTransfer.java]: log on OverWriteException

File: infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/StateTransfer.java [hunk 29]
```diff
@@ -30,96 +33,197 @@ private StateTransfer() {
...
+     *
+     * @param layout   Current layout.
+     * @param runtime  Corfu runtime instance.
+     * @param endpoint Endpoint ot transfer data to.
+     * @return Trim Address.
+     */
+    private static long setTrimOnNewLogUnit(Layout layout, CorfuRuntime runtime,
+                                            String endpoint) {
+
+        long trimMark = runtime.getAddressSpaceView().getTrimMark().getSequence();
```
Comment (Maithem) [inline infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/StateTransfer.java]: This can execute on a different layout, but subsequent calls don't. Why not call this with a runtime layout?

Also, what happens if there are other intermittent failures other than WrongEpochException ?

File: infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/StateTransfer.java (hunk 27 above)
Comment (Maithem) [reply infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/StateTransfer.java]: Since `transferChunk` accesses the first and last index of the list, it assumes that the list is not empty.
It would make sense to move this check in side  the `transferChunk` method.

File: infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/StateTransfer.java [hunk 30]
```diff
@@ -30,96 +33,197 @@ private StateTransfer() {
...
+     * @param chunk    List of addresses to be read and transferred.
+     */
+    private static void transferChunk(Layout layout,
+                                      CorfuRuntime runtime,
+                                      String endpoint,
+                                      List<Long> chunk) {
+        long ts1 = System.currentTimeMillis();
+
+        Map<Long, ILogData> dataMap = runtime.getAddressSpaceView()
+                .fetchAll(chunk, true);
```
Comment (Maithem) [inline infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/StateTransfer.java]: @WenbinZhu please make sure you change this.

File: infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/StateTransfer.java (hunk 27 above)
Comment (zalokhan) [reply infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/StateTransfer.java]: Moved the check to transferChunk.
That is already being logged in getMissingEntries.

File: runtime/src/main/java/org/corfudb/runtime/clients/LogUnitHandler.java [hunk 31]
```diff
@@ -213,4 +214,18 @@ private static Object handleTrimMarkResponse(CorfuPayloadMsg<Long> msg,
...
+    /**
+     * Handle a KNOWN_ADDRESS_RESPONSE message.
+     *
+     * @param msg Incoming Message
+     * @param ctx Context
+     * @param r   Router
+     * @return KnownAddressResponse payload with the missing addresses set.
+     */
+    @ClientHandler(type = CorfuMsgType.KNOWN_ADDRESS_RESPONSE)
+    private static Object handleMissingAddressesResponse(CorfuPayloadMsg<KnownAddressResponse> msg,
```
[the remark this answers is not in the document]
Comment (zalokhan) [reply runtime/src/main/java/org/corfudb/runtime/clients/LogUnitHandler.java]: Done.

File: infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/StateTransfer.java (hunk 29 above)
Comment (zalokhan) [reply infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/StateTransfer.java]: The reads are on the AddressSpaceView layer to abstract the replication layer and also the exceptions are taken care of.
This exposes a TrimException on which the action fails and is retried with the new trim mark.
WrongEpochExceptions should be just retried. Similarly, NetworkExceptions, Timeouts.
The writes do not use this layoutHelper method and hence are aborted if any exception is hit.
I haven't modified this functionality in this PR. I will address that in the next PR with appropriate testing.
