### PR TITLE
Fix stateTransfer and mergeSegment

### LINKED ISSUE #1178: Layout cleanup in case of split segment without merge
## Overview
In case of Add and Heal node workflows, there can be cases where the workflow able to split the segment and add the node back to the layout but is not able to merge these segments to restore redundancy.
There should be another task handled by the Management Server which detects these split segments and dispatches a workflow to merge them.

## Deliverables
- [ ] Detect split segments and merge them.

### PR DESCRIPTION
**Pull request by zalokhan**
## Overview

Description:
Addressing the following issues. #1178 
Modifying the add node workflow to replace the state transfer and merge segment Actions with the RestoreRedundancy Action.
This action takes the new endpoint to be added and restores its redundancy across all segments.
This is done by transferring the state of each of these segments to the new node. The end result is that now the new node is added as a part of all these segments. (Side effect: 1 epoch change.)
Note: After an add node, there will be multiple segments. The merging of segments will now only be handled by the Heal node workflow.

Modifying the heal node workflow to replace the state transfer and merge segment Actions with the RestoreRedundancyAndMergeSegments Action.
This action attempts to merge all the existing segments. In order to do so it finds out the incomplete logunit servers (logunits which are not present in all segments), transfers the required state so that all log units have the same data and finally merges the segments 2 at a time starting from the oldest.
(Side effect: To merge n segments, we have n-1 epoch increments.)

Why should this be merged: 

Related issue(s) (if applicable): Fixes #1178  

## Checklist (Definition of Done):

- [x] There are no TODOs left in the code
- [x] [Coding conventions](https://github.com/CorfuDB/CorfuDB/wiki/Corfu-Style-Guidelines) (e.g. for logging, unit tests) have been followed
- [x] Change is covered by automated tests
- [x] Public API has Javadoc

### CODE REVIEW

File: infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/workflows/AddNodeWorkflow.java [hunk 1]
```diff
@@ -162,54 +163,70 @@ private void stateTransfer(String endpoint, CorfuRuntime runtime,
...
-        public void impl(@Nonnull CorfuRuntime runtime) throws Exception {
-            runtime.getLayoutManagementView().mergeSegments(newLayout);
+                final int stripeIndex = 0;
+                runtime.getLayoutManagementView()
+                        .addLogUnitReplica(
+                                new Layout(newLayout), request.getEndpoint(), stripeIndex);
+                runtime.invalidateLayout();
+                newLayout = runtime.getLayoutView().getLayout();
+            } else {
+                throw new RuntimeException("Node to be added marked unresponsive.");
```
Comment (corfu-repo) [inline infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/workflows/AddNodeWorkflow.java]: MAJOR Define and throw a dedicated exception instead of using a generic one. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS00112)

**Comment by corfu-repo** [comment]
SonarQube analysis reported 1 issue
* ![MAJOR][MAJOR] 1 major

Watch the comments in this conversation to review them.

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

File: infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/workflows/HealNodeWorkflow.java [hunk 2]
```diff
@@ -89,4 +92,39 @@ public void impl(@Nonnull CorfuRuntime runtime) throws Exception {
...
+        public String getName() {
+            return "RestoreRedundancyAndMergeSegments";
+        }
+
+        @Override
+        public void impl(@Nonnull CorfuRuntime runtime) throws Exception {
+            while (newLayout.getSegments().size() > 1) {
+
+                // Catchup all servers.
+                Set<String> lowRedundancyServers = Sets.difference(
```
Comment (medhavidhawan) [inline infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/workflows/HealNodeWorkflow.java]: This is not correct . You are catching up all servers from all stripes.But actually it should be only all servers per stripe ? Or are we saying replicas are per segment ?

File: runtime/src/main/java/org/corfudb/runtime/view/LayoutManagementView.java [hunk 3]
```diff
@@ -222,14 +218,42 @@ public boolean mergeSegments(Layout currentLayout)
...
+     *
+     * @param currentLayout Current layout.
+     * @param endpoint      Endpoint to be added to the segment.
+     * @param stripeIndex   Stripe index.
+     * @throws OutrankedException if consensus is outranked.
+     */
+    public void addLogUnitReplica(@Nonnull Layout currentLayout,
+                                  @Nonnull String endpoint,
+                                  int stripeIndex) throws OutrankedException {
+        boolean isTaskDone = currentLayout.getSegments().stream()
```
Comment (medhavidhawan) [inline runtime/src/main/java/org/corfudb/runtime/view/LayoutManagementView.java]: needs more comment as these methods are too verbose and method names too layout specific to convey the intent.

File: test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java [hunk 4]
```diff
@@ -933,4 +941,261 @@ public void testAddNodeWithoutCatchup() throws Exception {
...
+     * Epoch 4
+     * Segment 1: 0 -> 9 (exclusive) Node 0, Node 1
+     * Segment 2: 9 -> infinity (exclusive) Node 0, Node 1, Node 2
+     *
+     * Epoch 5
+     * Segment 1: 0 -> infinity (exclusive) Node 0, Node 1, Node 2
+     * Finally the state transfer is verified by asserting all 3 nodes' data.
+     */
+    @Test
+    public void verifyStateTransferAndMergeInHeal() throws Exception {
```
Comment (medhavidhawan) [inline test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java]: good tests.

File: infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/workflows/AddNodeWorkflow.java [hunk 5]
```diff
@@ -121,21 +124,19 @@ public void impl(@Nonnull CorfuRuntime runtime) throws Exception {
...
-            return;
-
         }
     }
 
     /**
-     * Transfer an address segment from a cluster to a new node. The epoch shouldn't change
-     * during the segment transfer.
+     * Transfer an address segment from a cluster to a set of specified nodes. The epoch shouldn't
+     * change during the segment transfer.
```
[the remark this answers is not in the document]
Comment (zalokhan) [reply infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/workflows/AddNodeWorkflow.java]: It means that this method has no side effects on the epoch. Only state transfer without any reconfigurations. I'll clarify the comment.

File: infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/workflows/HealNodeWorkflow.java (hunk 2 above)
Comment (zalokhan) [reply infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/workflows/HealNodeWorkflow.java]: We have state transfer at the segment granularity and not for stripes.
Added comment.

File: runtime/src/main/java/org/corfudb/runtime/view/LayoutManagementView.java (hunk 3 above)
Comment (zalokhan) [reply runtime/src/main/java/org/corfudb/runtime/view/LayoutManagementView.java]: Done.

File: infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/workflows/HealNodeWorkflow.java [hunk 6]
```diff
@@ -89,4 +92,43 @@ public void impl(@Nonnull CorfuRuntime runtime) throws Exception {
...
+            return "RestoreRedundancyAndMergeSegments";
+        }
+
+        @Override
+        public void impl(@Nonnull CorfuRuntime runtime) throws Exception {
+            // Catchup all servers across all segments.
+            while (newLayout.getSegments().size() > 1) {
+
+                // Currently the state is transferred for the complete segment.
+                // TODO: Add stripe specific transfer granularity for optimization.
```
Comment (corfu-repo) [inline infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/workflows/HealNodeWorkflow.java]: INFO Complete the task associated to this TODO comment. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1135)

File: infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/workflows/AddNodeWorkflow.java (hunk 1 above)
Comment (corfu-repo) [inline infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/workflows/AddNodeWorkflow.java]: MAJOR Define and throw a dedicated exception instead of using a generic one. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS00112)

**Comment by corfu-repo** [comment]
SonarQube analysis reported 6 issues
* ![MAJOR][MAJOR] 1 major
* ![MINOR][MINOR] 4 minor
* ![INFO][INFO] 1 info

Watch the comments in this conversation to review them.

#### 4 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MINOR][MINOR] [ManagementView.java#L7](https://github.com/CorfuDB/CorfuDB/blob/93d5c086125cb2472ab86ca438d4416962baf5b9/runtime/src/main/java/org/corfudb/runtime/view/ManagementView.java#L7): Remove this unused import 'java.util.concurrent.Callable'. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AUselessImportCheck)
1. ![MINOR][MINOR] [ManagementView.java#L9](https://github.com/CorfuDB/CorfuDB/blob/93d5c086125cb2472ab86ca438d4416962baf5b9/runtime/src/main/java/org/corfudb/runtime/view/ManagementView.java#L9): Remove this unused import 'java.util.function.Predicate'. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AUselessImportCheck)
1. ![MINOR][MINOR] [ManagementView.java#L10](https://github.com/CorfuDB/CorfuDB/blob/93d5c086125cb2472ab86ca438d4416962baf5b9/runtime/src/main/java/org/corfudb/runtime/view/ManagementView.java#L10): Remove this unused import 'java.util.function.Supplier'. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AUselessImportCheck)
1. ![MINOR][MINOR] [ManagementView.java#L62](https://github.com/CorfuDB/CorfuDB/blob/93d5c086125cb2472ab86ca438d4416962baf5b9/runtime/src/main/java/org/corfudb/runtime/view/ManagementView.java#L62): Remove the declaration of thrown exception 'org.corfudb.runtime.exceptions.NetworkException' which is a runtime exception. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

File: infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/workflows/HealNodeWorkflow.java [hunk 7]
```diff
@@ -89,4 +92,43 @@ public void impl(@Nonnull CorfuRuntime runtime) throws Exception {
...
+                // Get the set of servers present in the second segment but not in the first
+                // segment.
+                Set<String> lowRedundancyServers = Sets.difference(
+                        newLayout.getSegments().get(1)
```
Comment (no2chem) [inline infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/workflows/HealNodeWorkflow.java]: Perhaps a segment should have a method to get all servers in that segment?

File: infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/workflows/AddNodeWorkflow.java (hunk 1 above)
Comment (no2chem) [reply infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/workflows/AddNodeWorkflow.java]: Can we define a new exception type here?

File: infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/workflows/HealNodeWorkflow.java (hunk 7 above)
Comment (zalokhan) [reply infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/workflows/HealNodeWorkflow.java]: Done.

**Comment by zalokhan** [comment]
All exceptions are caught by the orchestrator and it does not classify these. So I did not add a new exception class. The orchestrator then retries the action.
Let me know if you still think a new exception would help. I can add it.

**Comment by zalokhan** [comment]
@no2chem Addressed your comment.

**Comment by zalokhan** [comment]
Had to change `getSegmentsForEndpoint` to return list instead of set as there can be duplicate segments with the same start and end address which would later be collapsed by healing workflow but would cause addNode to fail.

File: infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/workflows/HealNodeWorkflow.java [hunk 8]
```diff
@@ -89,4 +92,37 @@ public void impl(@Nonnull CorfuRuntime runtime) throws Exception {
...
+            return "RestoreRedundancyAndMergeSegments";
+        }
+
+        @Override
+        public void impl(@Nonnull CorfuRuntime runtime) throws Exception {
+            // Catchup all servers across all segments.
+            while (newLayout.getSegments().size() > 1) {
+
+                // Currently the state is transferred for the complete segment.
+                // TODO: Add stripe specific transfer granularity for optimization.
```
Comment (corfu-repo) [inline infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/workflows/HealNodeWorkflow.java]: INFO Complete the task associated to this TODO comment. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1135)

File: infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/workflows/HealNodeWorkflow.java [hunk 9]
```diff
@@ -2,8 +2,12 @@
 
 import static org.corfudb.protocols.wireprotocol.orchestrator.OrchestratorRequestType.HEAL_NODE;
 
+import com.google.common.collect.Sets;
+
 import java.util.Arrays;
 import java.util.List;
+import java.util.Set;
+import java.util.stream.Collectors;
```
Comment (corfu-repo) [inline infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/workflows/HealNodeWorkflow.java]: MINOR Remove this unused import 'java.util.stream.Collectors'. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AUselessImportCheck)

File: infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/workflows/AddNodeWorkflow.java [hunk 10]
```diff
@@ -162,54 +163,71 @@ private void stateTransfer(String endpoint, CorfuRuntime runtime,
...
-        public void impl(@Nonnull CorfuRuntime runtime) throws Exception {
-            runtime.getLayoutManagementView().mergeSegments(newLayout);
+                final int stripeIndex = 0;
+                runtime.getLayoutManagementView()
+                        .addLogUnitReplica(
+                                new Layout(newLayout), request.getEndpoint(), stripeIndex);
+                runtime.invalidateLayout();
+                newLayout = runtime.getLayoutView().getLayout();
+            } else {
+                throw new RuntimeException("RestoreRedundancy: "
```
Comment (corfu-repo) [inline infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/workflows/AddNodeWorkflow.java]: MAJOR Define and throw a dedicated exception instead of using a generic one. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS00112)

**Comment by corfu-repo** [comment]
SonarQube analysis reported 3 issues
* ![MAJOR][MAJOR] 1 major
* ![MINOR][MINOR] 1 minor
* ![INFO][INFO] 1 info

Watch the comments in this conversation to review them.

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'
