### PR TITLE
Terminating sequencerBootstrap thread on shutdown

### LINKED ISSUE #1439: SequencerBootstrapTask cannot be shutdown.
## Overview

The asynchronous task executing the sequencer recovery by running the FastObjectLoader cannot be interrupted since its submitted to the ForkJoinPool. This task self-aborts using the systemDownHandler after 60 seconds.
However, several tests are timing out due to this behaviour causing CI to fail intermittently.
We can use a `cachedThreadPool` which gives us a better control over this thread.

### PR DESCRIPTION
**Pull request by zalokhan**
## Overview

Description: Submitting sequencer bootstrap tasks to the detectionWorker thread pool instead of ForkJoinPool to better control the termination of this task.

Why should this be merged: On shut down the task runs asynchronously. 

Related issue(s) (if applicable): Fixes #1439 

## Checklist (Definition of Done):

- [x] There are no TODOs left in the code
- [x] [Coding conventions](https://github.com/CorfuDB/CorfuDB/wiki/Corfu-Style-Guidelines) (e.g. for logging, unit tests) have been followed
- [x] Change is covered by automated tests
- [x] Public API has Javadoc

### CODE REVIEW

File: infrastructure/src/main/java/org/corfudb/infrastructure/ManagementAgent.java [hunk 1]
```diff
@@ -223,6 +228,15 @@
                         .setNameFormat(serverContext.getThreadPrefix() + "LocalMetricsPolling")
                         .build());
 
+        // Creating a cached thread pool to spawn a task to bootstrap the sequencer. The number of
+        // tasks submitted to this thread pool is limited to one. We check if we have an ongoing
+        // task before we launch a new one.
+        this.sequencerBootstrapWorker = Executors.newCachedThreadPool(
```
Comment (Maithem) [inline infrastructure/src/main/java/org/corfudb/infrastructure/ManagementAgent.java]: This class has too many thread pools, why is this needed?  Why not reuse the detectionTaskWorkers pool? Also, why is this a cched thread pool, if all you want to do is cancel a task, you can use a single threaded executor.

File: infrastructure/src/main/java/org/corfudb/infrastructure/ManagementAgent.java [hunk 2]
```diff
@@ -242,12 +256,12 @@
...
      *
      * @param layout Layout to use to bootstrap the primary sequencer.
-     * @return Completable future which completes when the task completes successfully or with a
-     * failure.
+     * @return Future which completes when the task completes successfully or with a failure.
      */
-    public CompletableFuture<Boolean> triggerSequencerBootstrap(@NonNull Layout layout) {
+    public Future<Boolean> triggerSequencerBootstrap(@NonNull Layout layout) {
         if (sequencerRecoveryFuture.isDone()) {
-            this.sequencerRecoveryFuture = CompletableFuture.supplyAsync(() -> {
```
Comment (Maithem) [inline infrastructure/src/main/java/org/corfudb/infrastructure/ManagementAgent.java]: I see, this spawns non-daemon threads.

File: infrastructure/src/main/java/org/corfudb/infrastructure/ManagementAgent.java (hunk 1 above)
Comment (zalokhan) [reply infrastructure/src/main/java/org/corfudb/infrastructure/ManagementAgent.java]: I can reuse the detectionWorkers pool by supplying it an extra thread.
I used the cached thread pool to optimize for thread resources and return the thread once the task is completed.
In a good scenario where we have minimal epoch changes, this thread will be wasted.

Comment (Maithem) [reply infrastructure/src/main/java/org/corfudb/infrastructure/ManagementAgent.java]: Optimize as needed. 

Are you saying that newCachedThreadPool will destroy the thread if its not being used?

Comment (Maithem) [reply infrastructure/src/main/java/org/corfudb/infrastructure/ManagementAgent.java]: I see. I don't think this optimization is necessary.

Comment (zalokhan) [reply infrastructure/src/main/java/org/corfudb/infrastructure/ManagementAgent.java]: Ok, I'll add a thread to detectionWorkersPool then.

File: infrastructure/src/main/java/org/corfudb/infrastructure/ManagementAgent.java [hunk 3]
```diff
@@ -242,12 +256,12 @@
      * a task in progress, this is a no-op.
      *
      * @param layout Layout to use to bootstrap the primary sequencer.
-     * @return Completable future which completes when the task completes successfully or with a
-     * failure.
+     * @return Future which completes when the task completes successfully or with a failure.
      */
-    public CompletableFuture<Boolean> triggerSequencerBootstrap(@NonNull Layout layout) {
+    public Future<Boolean> triggerSequencerBootstrap(@NonNull Layout layout) {
```
Comment (StrikingThirteen) [inline infrastructure/src/main/java/org/corfudb/infrastructure/ManagementAgent.java]: I know that this method is not being used outside ManagementAgent, yet this is a breaking change of interface. Can we avoid it? Also if it is not needed to be public, now that the interface is changing maybe consider narrowing the visibility of triggerSequenceBootstrap method

File: infrastructure/src/main/java/org/corfudb/infrastructure/ManagementAgent.java (hunk 1 above)
Comment (StrikingThirteen) [reply infrastructure/src/main/java/org/corfudb/infrastructure/ManagementAgent.java]: @Maithem If we are going to increase the detection thread pool size why not just using SingleThreadExecutor? @zalokhan Although cached thread pool shed their non-core threads, the Executor's default has unlimited max. to take the same benefit maybe consider:
`this.sequencerBootstrapWorker = new ThreadPoolExecutor(0, 1,  
                                                      60, TimeUnit.SECONDS, 
                                                       aQueue, aThreadFactory); `

It has an upper limit of 1 which is semantically inline with logic of the bootstrapping (no more than 1 bootstrapping task) and it has 0 core thread.

File: infrastructure/src/main/java/org/corfudb/infrastructure/ManagementAgent.java [hunk 4]
```diff
@@ -792,6 +807,7 @@ public void shutdown() {
         detectionTasksScheduler.shutdownNow();
         detectionTaskWorkers.shutdownNow();
         localMetricsPollingService.shutdownNow();
+        sequencerBootstrapWorker.shutdownNow();
```
Comment (StrikingThirteen) [inline infrastructure/src/main/java/org/corfudb/infrastructure/ManagementAgent.java]: Not sure, if you are going to keep all four. but in that case, maybe a method that takes a collection of thread pools and shut them might be more readable. (same for awaitTermination)

File: infrastructure/src/main/java/org/corfudb/infrastructure/ManagementAgent.java [hunk 5]
```diff
@@ -256,8 +256,9 @@
                 }
                 return true;
             });
+        } else {
+            log.info("triggerSequencerBootstrap: a bootstrap task is already in progress.");
```
Comment (medhavidhawan) [inline infrastructure/src/main/java/org/corfudb/infrastructure/ManagementAgent.java]: this is predicated on the fact that the function is being called in a single threaded manner. Please improve this.

**Comment by zalokhan** [comment]
@medhavidhawan Fixed the sequencer trigger on a node to be atomic.

File: runtime/src/main/java/org/corfudb/util/concurrent/SingletonResource.java [hunk 6]
```diff
@@ -1,102 +1,78 @@
...
-    /** Generate a new {@link SingletonResource}.
+    /**
+     * Generate a new {@link SingletonResource}.
      *
-     * @param generator     A method to be called when a new {@link T} is needed.
+     * @param generator A method to be called when a new {@link T} is needed.
      */
     private SingletonResource(Supplier<T> generator) {
-        lock = new StampedLock();
+        this.resource = new AtomicReference<T>();
```
Comment (corfu-repo) [inline runtime/src/main/java/org/corfudb/util/concurrent/SingletonResource.java]: MINOR Replace the type specification in this constructor call with the diamond operator ("<>"). [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS2293)

**Comment by corfu-repo** [comment]
SonarQube analysis reported 1 issue
* ![MINOR][MINOR] 1 minor

Watch the comments in this conversation to review them.

[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by annym** [comment]
We might need to update the overview description of this PR (commit message) so it actually matches with the final implementation and avoid discrepancies or quick assumptions in the future.
