### PR TITLE
Prevent NetworkException from causing a double-write

### LINKED ISSUE #974: Transaction aborted happens to be committed
If there is a network exception during the chain replication write of the transaction entry, the network exception gets propagated as a transactionAbortedException. Transaction aborted should mean that the transaction was not committed.

The problem is that doesn't mean the transaction was aborted because if at least one node of the chain successfully wrote the entry, hole filling will likely propagate it to the other logUnits (if the logUnit that contains it is still part of the layout).

The Fix will block the client infinitely until it finishes its transaction. We also converged on having a parameter for debugging purpose to set a timeout.

### PR DESCRIPTION
**Pull request by rogermichoud**
The Runtime has a settable timeout for how long it will wait for
an unavailable system. If we are not able to progress (due to NetworkExcpetion)
during the timeout, the handler provided by the client (or default handler,
that shutdown the Runtime) will be triggered.

Fixes #974

### CODE REVIEW

File: runtime/src/main/java/org/corfudb/runtime/view/AbstractView.java [hunk 1]
```diff
@@ -97,6 +105,13 @@ public Layout getCurrentLayout() {
                     log.warn("Got a wrong epoch exception, updating epoch to {} and "
                             + "invalidate view", we.getCorrectEpoch());
                     runtime.invalidateLayout();
+                } else if(re instanceof NetworkException) {
+                    try {
+                        Thread.sleep(runtime.retryRate * 1000);
+                    } catch (InterruptedException e) {
+                        log.warn("Interrupted Exception in layout helper.", e);
+                    }
+                    log.warn("System seems unavailable");
```
Comment (no2chem) [inline runtime/src/main/java/org/corfudb/runtime/view/AbstractView.java]: Correct format is getCurrentLayout: x

**Comment by rogermichoud** [comment]
@no2chem 
The problem is that there are many threads that are executing AbstractView layoutHelper. In order to implement a timeout crafted in the handler, I would need to use ThreadLocals and add variables to my default implementation of the handler in CorfuRuntime. Doesn't look that clean to me.

What I can do instead is pass the timeout parameter with the handler. Like this, if somebody wants to register a handler that fires directly, he can pass a -1 for the timeout.

**Comment by no2chem** [comment]
@rogermichoud I'm not sure why threadlocals are necessary. 
Timeouts should still be decided globally on a per-request basis. The handler should get the NetworkException, and decide what to do; this doesn't need to be on a per-thread basis, in fact, it shouldn't be --- it should be on a per-endpoint basis. 

By default, there should be no handler (i.e., the handler should always return).

**Comment by rogermichoud** [comment]
@no2chem 
You want the default behavior to hang forever? I thought the consensus was having the default behavior to shutdown the runtime after a timeout (SystemUnavailable state).

**Comment by no2chem** [comment]
Yes, the default behavior should be to (retry, not hang) forever. If there is an application which has a specific behavior requirement (e.g., mp, they may specify it using the handler).

File: test/src/test/java/org/corfudb/runtime/CorfuRuntimeTest.java [hunk 2]
```diff
@@ -173,4 +177,62 @@ public void doesNotAllowReadsAfterSealAndBeforeNewLayout() throws Exception {
...
+     * a SystemUnavailableException is thrown and the runtime is shutdown.
+     *
+     * @throws Exception
+     */
+    @Test
+    public void customNetworkExceptionHandler() throws Exception {
+        class TimeoutHandler {
+            CorfuRuntime rt;
+            long maxTimeout;
+            ThreadLocal<Long> localTimeStart = new ThreadLocal<>();
```
[the remark this answers is not in the document]
Comment (rogermichoud) [reply test/src/test/java/org/corfudb/runtime/CorfuRuntimeTest.java]: Well this is an example, so I guess there is some freedom on how to implement it. I also think different threads could be interacting with different routers. If one thread is only reading, its queries will only go to the chain tail, and it will reset the timer each time. This could mask a problem with writes that could never go in.

File: runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java [hunk 3]
```diff
@@ -84,6 +84,34 @@ public void resetCaches() {
...
+     * @param address
+     */
+    private void validateStateOfWrittenEntry(long address) {
+        ILogData logData;
+        try {
+            logData = read(address);
+        } catch (TrimmedException te) {
+            // We cannot know if the write went through or not
+            // This will rewrite
+            throw new OverwriteException();
```
[the remark this answers is not in the document]
Comment (rogermichoud) [reply runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java]: I want to throw your UnrecoverableCorfuException. That will just create a dependency on your PR. Which is fine. The UnreceoverableCorfruExcpetion should go in pretty soon.

[the remark this answers is not in the document]
Comment (no2chem) [reply runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java]: Sounds good.. It's UnrecoverableCorfuError now :). Can you create a dependency on ZenHub so we can track it?

File: runtime/src/main/java/org/corfudb/runtime/view/AbstractView.java [hunk 4]
```diff
@@ -93,14 +110,38 @@ public Layout getCurrentLayout() {
                     log.warn("Got a wrong epoch exception, updating epoch to {} and "
                             + "invalidate view", we.getCorrectEpoch());
                     runtime.invalidateLayout();
+                } else if (re instanceof NetworkException) {
```
Comment (corfu-repo) [inline runtime/src/main/java/org/corfudb/runtime/view/AbstractView.java]: MAJOR Replace the usage of the "instanceof" operator by a catch block. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1193)

File: runtime/src/main/java/org/corfudb/runtime/view/AbstractView.java [hunk 5]
```diff
@@ -93,14 +110,38 @@ public Layout getCurrentLayout() {
...
+                        Thread.sleep(runtime.retryRate * 1000);
+                    } catch (InterruptedException e) {
+                        log.warn("Interrupted Exception in layout helper.", e);
+                    }
+
                 } else {
                     throw re;
                 }
+                if (rethrowAllExceptions) {
+                    throw new RuntimeException(re);
```
Comment (corfu-repo) [inline runtime/src/main/java/org/corfudb/runtime/view/AbstractView.java]: MAJOR Define and throw a dedicated exception instead of using a generic one. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS00112)

File: runtime/src/main/java/org/corfudb/runtime/view/AbstractView.java [hunk 6]
```diff
@@ -93,14 +110,38 @@ public Layout getCurrentLayout() {
...
+
+                // If SystemUnavailable exception is thrown by the layout.get() completable future,
+                // the exception will materialize as an ExecutionException. In that case, we need to propagate
+                // this exception.
+                if (ex.getCause() instanceof SystemUnavailableException) {
+                    throw (SystemUnavailableException) ex.getCause();
+                }
+
                 runtime.invalidateLayout();
                 Utils.sleepUninterruptibly(runtime.retryRate * 1000);
```
Comment (corfu-repo) [inline runtime/src/main/java/org/corfudb/runtime/view/AbstractView.java]: MINOR Cast one of the operands of this multiplication operation to a "long". [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS2184)

File: runtime/src/main/java/org/corfudb/runtime/view/AbstractView.java [hunk 7]
```diff
@@ -58,24 +60,39 @@ public Layout getCurrentLayout() {
...
      * @param <D>      Any exception the function may throw.
+     * @param rethrowAllExceptions if all exceptions are rethrown to caller.
      * @return The return value of the function.
      */
     public <T, A extends RuntimeException, B extends RuntimeException, C extends RuntimeException,
             D extends RuntimeException> T layoutHelper(LayoutFunction<Layout, T, A, B, C, D>
-                                                                          function)
+                                                                          function,
+                                                       boolean rethrowAllExceptions)
             throws A, B, C, D {
```
Comment (corfu-repo) [inline runtime/src/main/java/org/corfudb/runtime/view/AbstractView.java]: MINOR Remove the declaration of thrown exception 'A' which is a runtime exception. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)
MINOR Remove the declaration of thrown exception 'B' which is a runtime exception. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)
MINOR Remove the declaration of thrown exception 'C' which is a runtime exception. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)
MINOR Remove the declaration of thrown exception 'D' which is a runtime exception. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)

File: runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java [hunk 8]
```diff
@@ -238,6 +245,31 @@ public CorfuRuntime setMetrics(@NonNull MetricRegistry metrics) {
...
+     * These two handlers are provided to give some control on what happen when system is down.
+     *
+     * For applications that want to have specific behaviour when a the system appears unavailable, they can
+     * register their own handler for both before the rpc request and upon network exception.
+     *
+     * An example of how to use these handlers implementing timeout is given in
+     * test/src/test/java/org/corfudb/runtime/CorfuRuntimeTest.java
+     *
+     */
+    public Runnable beforeRpcHandler = () -> {};
```
Comment (corfu-repo) [inline runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java]: MAJOR Either remove or fill this block of code. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS00108)
MINOR Make beforeRpcHandler a static final constant or non-public and provide accessors if needed. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)

File: runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java [hunk 9]
```diff
@@ -238,6 +245,31 @@ public CorfuRuntime setMetrics(@NonNull MetricRegistry metrics) {
...
+    public Runnable systemDownHandler = () -> {};
```
Comment (corfu-repo) [inline runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java]: MAJOR Either remove or fill this block of code. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS00108)
MINOR Make systemDownHandler a static final constant or non-public and provide accessors if needed. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)

File: runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java [hunk 10]
```diff
@@ -111,12 +140,23 @@ public void write(IToken token, Object data) throws OverwriteException {
...
             // Do the write
-            l.getReplicationMode(token.getTokenValue())
+            try {
+                l.getReplicationMode(token.getTokenValue())
                         .getReplicationProtocol(runtime)
                         .write(l, ld);
+            } catch (RuntimeException re) {
+                // These two exceptions are pass through. Both of them are already too late for trying
+                // to validate the state of the write, we know that it didn't went through.
+                if (re instanceof SystemUnavailableException || re instanceof OverwriteException) {
```
Comment (corfu-repo) [inline runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java]: MAJOR Replace the usage of the "instanceof" operator by a catch block. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1193)
MAJOR Replace the usage of the "instanceof" operator by a catch block. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1193)

File: runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java [hunk 11]
```diff
@@ -111,12 +140,23 @@ public void write(IToken token, Object data) throws OverwriteException {
...
+                    throw re;
+                }
+                re.printStackTrace();
```
Comment (corfu-repo) [inline runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java]: MINOR Use a logger to log this exception. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1148)

File: test/src/test/java/org/corfudb/integration/ServerRestartIT.java [hunk 12]
```diff
@@ -262,15 +264,30 @@ private void runSingleNodeRecoveryTransactionalClient(boolean nested) throws Exc
...
+                if (!txState) {
+                    return false;
+                };
+            }
+
+            return true;
+        },CLIENT_DELAY_POST_SHUTDOWN, TimeUnit.MILLISECONDS);
+        offline.shutdown();
+
+        Thread.sleep(CORFU_SERVER_DOWN_TIME);
```
Comment (corfu-repo) [inline test/src/test/java/org/corfudb/integration/ServerRestartIT.java]: MAJOR Remove this use of "Thread.sleep()". [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS2925)

**Comment by corfu-repo** [comment]
SonarQube analysis reported 16 issues
* ![MAJOR][MAJOR] 8 major
* ![MINOR][MINOR] 8 minor

Watch the comments in this conversation to review them.

#### 1 extra issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [CorfuRuntime.java#L586](https://github.com/CorfuDB/CorfuDB/blob/149e859ec66c4ce95034f8f84db16ff8a175e02e/runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java#L586): Either re-interrupt this method or rethrow the "InterruptedException". [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS2142)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by corfudb-performance** [comment]
Results automatically generated by _CorfuDB Benchmark Framework_ to assess the performance of this pull request for commit **149e859**.

*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 1 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 5 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 10 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 1 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 5 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 10 threads, Disk mode
 
 An interactive dashboard with Pull Request Performance Metrics for ALL cluster types and numbers of threads in run, is available at:
 [Pull Request #982 Graphs ](https://snapshot.raintank.io/dashboard/snapshot/Ge7F5tXx7oTVKDfOUzlv5tEBPIcDh5WQ)

File: runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java (hunk 11 above)
Comment (no2chem) [reply runtime/src/main/java/org/corfudb/runtime/view/AddressSpaceView.java]: Remove this printStackTrace

**Comment by rogermichoud** [comment]
@no2chem I had to do some tweaks to tests and also be sure that the custom handler would get out of fetchLayout as well if we cannot reach any layout. Should not impact the default path.

Also I wanted to be sure we handle both cases correctly for custom handlers:
     1. We cannot write because one (or more) server of the logunit chain is not reachable but we can get a layout (some or all layout servers are up).
     2. We cannot write and we cannot have a layout. In that case, we are stuck in fetchLayout.

if the changes are ok for you, we can merge.

**Comment by rogermichoud** [comment]
@no2chem 
Also removed the printStackTrace

**Comment by no2chem** [comment]
Hm - Also, weren't you going to have SystemUnavailableException extend UnrecoverableCorfuError?

**Comment by rogermichoud** [comment]
Well, I wasn't but I will :-)

File: runtime/src/main/java/org/corfudb/runtime/view/AbstractView.java [hunk 13]
```diff
@@ -45,6 +45,8 @@ public Layout getCurrentLayout() {
         while (true) {
             try {
                 return runtime.layout.get();
+            } catch (SystemUnavailableException sue) {
```
Comment (no2chem) [inline runtime/src/main/java/org/corfudb/runtime/view/AbstractView.java]: This shouldn't be necessary, the error will not be caught by the exception catch block below

File: runtime/src/main/java/org/corfudb/runtime/exceptions/SystemUnavailableException.java [hunk 14]
```diff
@@ -0,0 +1,13 @@
+package org.corfudb.runtime.exceptions;
+
+import org.corfudb.runtime.exceptions.unrecoverable.UnrecoverableCorfuError;
+
+/**
+ * Created by rmichoud on 10/31/17.
+ */
+public class SystemUnavailableException extends UnrecoverableCorfuError {
```
Comment (no2chem) [inline runtime/src/main/java/org/corfudb/runtime/exceptions/SystemUnavailableException.java]: SystemUnavailableException -> SystemUnavailableError. Also you can move it to the Unrecoverable package.
