### PR TITLE
Kill node fix and IT

### LINKED ISSUE #1074: ITs are printing output when they shouldn't
## Overview

**Bug report.** Integration tests are printing to System.out when they should not be.

See example output:

```
unning org.corfudb.integration.ServerRestartIT
sequencerTailsRecoveryTest                                  [PASS]
discardTokenReceivedInPreviousEpoch                         [PASS]
testSingleNodeRecoveryTransactionalClientNested             SEED = dfa026782112e687
[PASS]
testSingleNodeRecoveryTransactionalClient                   SEED = 9e61ef048a3a35d8
[PASS]
testCorfuTableIndexReconstruction                           [PASS]
testRandomizedRecovery                                      SEED = 54028b07ae6091f4
Iteration #0
Iteration #1
Iteration #2
Iteration #3
```

### PR DESCRIPTION
**Pull request by zalokhan**
## Overview

Description: Fixes the kill node scenario and introduces an IT to test the same.
Issue: Writes blocked when a node containing a logunit and the primary sequencer crashes.
Fix: The maxGlobalTail fetch relied on fetching the tail from the crashed server. This caused failure in bootstrapping the new sequencer. So no new writes could get through.
Now the maxGlobalTail relies on fetching the global tail from the head of the chain of the new proposed layout. This ensures availability of the server and successfully bootstraps the sequencer.

Why should this be merged: Fixes kill node scenario and cleans up IT.

Related issue(s) (if applicable): Fixes #1074 

## Checklist (Definition of Done):

- [x] There are no TODOs left in the code
- [x] [Coding conventions](https://github.com/CorfuDB/CorfuDB/wiki/Corfu-Style-Guidelines) (e.g. for logging, unit tests) have been followed
- [x] Change is covered by automated tests
- [x] Public API has Javadoc

### CODE REVIEW

File: test/src/test/java/org/corfudb/integration/ClusterReconfigIT.java [hunk 1]
```diff
@@ -266,4 +285,90 @@ public void restartTest() throws Exception {
         assertThat(corfuRuntime.getLayoutView().getLayout().getEpoch()).isEqualTo(l.getEpoch() + 1);
         assertThat(shutdownCorfuServer(corfuServer)).isTrue();
     }
+
```
Comment (annym) [inline test/src/test/java/org/corfudb/integration/ClusterReconfigIT.java]: When running our kill node test, with this PR on top of latest master client hangs and test is never able to terminate (regardless of the node being killed, i.e., log unit with primary sequencer or different node).

File: test/src/test/java/org/corfudb/integration/ClusterReconfigIT.java [hunk 2]
```diff
@@ -266,4 +285,90 @@ public void restartTest() throws Exception {
...
+    /**
+     * Kill a node containing the head of the log unit chain and the primary sequencer.
+     * Ensures writes into after kill node and cluster re-stabilization.
+     *
+     * @throws Exception
+     */
+    @Test
```
Comment (annym) [inline test/src/test/java/org/corfudb/integration/ClusterReconfigIT.java]: We should also add a test for the case when a non-primary sequencer log unit is killed.

File: test/src/test/java/org/corfudb/integration/ClusterReconfigIT.java [hunk 3]
```diff
@@ -266,4 +285,90 @@ public void restartTest() throws Exception {
...
+        Thread.sleep(PARAMETERS.TIMEOUT_SHORT.toMillis());
+        final Layout layout = get3NodeLayout();
+        bootstrapCluster(layout);
+
+        // Create map and set up daemon writer thread.
+        CorfuRuntime runtime = createDefaultRuntime();
+        Map<String, String> map = runtime.getObjectsView()
+                .build()
+                .setStreamName("test")
+                .setType(SMRMap.class)
```
[the remark this answers is not in the document]
Comment (zalokhan) [reply test/src/test/java/org/corfudb/integration/ClusterReconfigIT.java]: Using CorfuTables

File: test/src/test/java/org/corfudb/integration/ClusterReconfigIT.java [hunk 4]
```diff
@@ -266,4 +285,90 @@ public void restartTest() throws Exception {
...
     }
+
+    /**
+     * Kill a node containing the head of the log unit chain and the primary sequencer.
+     * Ensures writes into after kill node and cluster re-stabilization.
+     *
+     * @throws Exception
+     */
+    @Test
+    public void killLogUnitAndPrimarySequencer() throws Exception {
```
[the remark this answers is not in the document]
Comment (zalokhan) [reply test/src/test/java/org/corfudb/integration/ClusterReconfigIT.java]: Added.

File: test/src/test/java/org/corfudb/integration/ClusterReconfigIT.java (hunk 2 above)
Comment (zalokhan) [reply test/src/test/java/org/corfudb/integration/ClusterReconfigIT.java]: Added.

File: test/src/test/java/org/corfudb/integration/ClusterReconfigIT.java (hunk 1 above)
Comment (zalokhan) [reply test/src/test/java/org/corfudb/integration/ClusterReconfigIT.java]: Resolved. The test framework was hanging as there was a change in the log directory.

File: runtime/src/main/java/org/corfudb/runtime/view/LayoutManagementView.java [hunk 5]
```diff
@@ -161,7 +164,7 @@ public void addNode(Layout currentLayout,
      * @throws OutrankedException          if consensus is outranked.
      */
```
[the remark this answers is not in the document]
Comment (zalokhan) [reply runtime/src/main/java/org/corfudb/runtime/view/LayoutManagementView.java]: Done.

File: test/src/test/java/org/corfudb/integration/ClusterReconfigIT.java [hunk 6]
```diff
@@ -266,4 +291,123 @@ public void restartTest() throws Exception {
...
+        final AtomicBoolean moreDataToBeWritten = new AtomicBoolean(true);
+        Thread t = startDaemonWriter(runtime, r, table, data, moreDataToBeWritten);
+
+        // Some preliminary writes into the corfu table.
+        for (int i = 0; i < PARAMETERS.NUM_ITERATIONS_MODERATE; i++) {
+            try {
+                runtime.getObjectsView().TXBegin();
+                table.put(Integer.toString(r.nextInt()), data);
+                runtime.getObjectsView().TXEnd();
+                break;
```
Comment (medhavidhawan) [inline test/src/test/java/org/corfudb/integration/ClusterReconfigIT.java]: what is the break for ?

Comment (zalokhan) [reply test/src/test/java/org/corfudb/integration/ClusterReconfigIT.java]: Not required. Removed.

**Comment by zalokhan** [comment]
@no2chem This is now ready. Can you merge this?
