### PR TITLE
Handle restore redundancy and merge segments.

### LINKED ISSUE #1390: Segments Don't Get Merged
**Bug report.**
The fault detector never merges the segmented address space after add node

root@nsx-manager:/var/log/cbm# cat /config/corfu/LAYOUT_CURRENT.ds 
ohW{
  "layoutServers": [
    "address1:9000",
    "address2:9000"
  ],
  "sequencers": [
    "address1:9000",
    "address2:9000"
  ],
  "segments": [
    {
      "replicationMode": "CHAIN_REPLICATION",
      "start": 0,
      "end": 162562,
      "stripes": [
        {
          "logServers": [
            "address1:9000",
            "address2:9000"
          ]
        }
      ]
    },
    {
      "replicationMode": "CHAIN_REPLICATION",
      "start": 162562,
      "end": -1,
      "stripes": [
        {
          "logServers": [
            "address1:9000",
            "address2:9000"
          ]
        }
      ]
    }
  ],
  "unresponsiveServers": [],
  "epoch": 2,
  "clusterId": "e9f4e79d-79e3-4c8c-be83-89adbbde76eb"
}

### PR DESCRIPTION
**Pull request by zalokhan**
## Overview

Description: Detect split segments, restore redundancy and merge the segments.

Why should this be merged: If the heal/add node workflow crashes midway, the state transfer is never completed and the newly added nodes stay with reduced redundancy.

Related issue(s) (if applicable): Fixes #1390 

## Checklist (Definition of Done):

- [x] There are no TODOs left in the code
- [x] [Coding conventions](https://github.com/CorfuDB/CorfuDB/wiki/Corfu-Style-Guidelines) (e.g. for logging, unit tests) have been followed
- [x] Change is covered by automated tests
- [x] Public API has Javadoc

### CODE REVIEW

File: infrastructure/src/main/java/org/corfudb/infrastructure/RemoteMonitoringService.java [hunk 1]
```diff
@@ -109,11 +110,18 @@
...
 
     /**
-     * Number of workers for failure detector. Two workers used by dafult:
+     * Number of workers for failure detector. Three workers used by default:
      * - failure/healing detection
      * - bootstrap sequencer
+     * - merge segments
      */
-    private final int detectionWorkersCount = 2;
+    private final int detectionWorkersCount = 3;
```
Comment (medhavidhawan) [inline infrastructure/src/main/java/org/corfudb/infrastructure/RemoteMonitoringService.java]: why do we need an extra thread ?

File: infrastructure/src/main/java/org/corfudb/infrastructure/RemoteMonitoringService.java [hunk 2]
```diff
@@ -360,12 +368,36 @@ private synchronized void runDetectionTasks() {
...
     }
 
+
+    /**
+     * Spawns a new task to merge segments if no task in progress.
+     *
+     * @return Detector task.
+     */
+    private DetectorTask mergeSplitSegments() {
+        Layout layout = serverContext.copyManagementLayout();
```
[the remark this answers is not in the document]
Comment (medhavidhawan) [reply infrastructure/src/main/java/org/corfudb/infrastructure/RemoteMonitoringService.java]: I agree we need more logging here.

File: infrastructure/src/main/java/org/corfudb/infrastructure/management/ReconfigurationEventHandler.java [hunk 3]
```diff
@@ -56,6 +59,28 @@ public static boolean handleFailure(@Nonnull IReconfigurationHandlerPolicy failu
         }
     }
 
+    /**
+     * Calculate a reasonable workflow timeout
+     *
+     * @param runtime Connected corfu runtime instance
+     * @return A reasonable timeout to complete state transfer and rebuild logging unit.
+     */
+    private static Duration getReasonableWorkflowTimeout(CorfuRuntime runtime) {
```
Comment (medhavidhawan) [inline infrastructure/src/main/java/org/corfudb/infrastructure/management/ReconfigurationEventHandler.java]: The name says Reasonable but that is a tall claim please use a better name. Also this is very static and does not learn from the last failure. Every iteration should learn from the previous failed iteration.

File: infrastructure/src/main/java/org/corfudb/infrastructure/management/ReconfigurationEventHandler.java [hunk 4]
```diff
@@ -56,6 +59,28 @@ public static boolean handleFailure(@Nonnull IReconfigurationHandlerPolicy failu
...
+        Token trimMark = runtime.getAddressSpaceView().getTrimMark();
+        long tail = runtime.getAddressSpaceView().getAllTails().getLogTail();
+
+        long rangeToReplicate = tail - trimMark.getSequence();
+        // Since the orchestrator client and the fault detector client use
+        // the same configuration its reasonable to use these arguments.
+        // TODO(Maithem): AddNode should use a similar mechanism to set the timeout
+        long numSections = rangeToReplicate / runtime.getParameters().getBulkReadSize();
+        long rpcTimeout = (long) (runtime.getParameters().getRequestTimeout().toMillis() * 1.5);
+        long timeoutInMs = Math.max(DEFAULT_HEAL_TIMEOUT.toMillis(), numSections * rpcTimeout);
```
Comment (medhavidhawan) [inline infrastructure/src/main/java/org/corfudb/infrastructure/management/ReconfigurationEventHandler.java]: there should be logging somewhere to tell what is the new workflow timeout.

File: infrastructure/src/main/java/org/corfudb/infrastructure/management/ReconfigurationEventHandler.java [hunk 5]
```diff
@@ -102,4 +116,32 @@ public static boolean handleHealing(@Nonnull CorfuRuntime runtime,
             return false;
         }
     }
+
+    /**
+     * Launches a workflow to restore redundancy and merge all segments.
```
Comment (medhavidhawan) [inline infrastructure/src/main/java/org/corfudb/infrastructure/management/ReconfigurationEventHandler.java]: Need more detailed comments. One liners are not sufficient.

File: infrastructure/src/main/java/org/corfudb/infrastructure/management/ReconfigurationEventHandler.java [hunk 6]
```diff
@@ -102,4 +116,32 @@ public static boolean handleHealing(@Nonnull CorfuRuntime runtime,
...
+        Duration workflowTimeout = getReasonableWorkflowTimeout(runtime);
+        log.info("triggerMergeSegments: Workflow to merge segments for layout {} timeout set to {} ms",
+                layout, workflowTimeout);
+
+        final Duration retryQueryTimeout = Duration.ofSeconds(1);
+
+        // Multiple invocations of this workflow can be avoided if the workflow are mapped to the same endpoint.
+        // Thus to deterministically choose an endpoint we always choose the last added log unit in the first stripe.
+        // Fetching the last segment. Note: This is the unbounded segment with ongoing writes.
+        LayoutSegment lastSegment = layout.getSegments().get(layout.getSegments().size() - 1);
```
Comment (medhavidhawan) [inline infrastructure/src/main/java/org/corfudb/infrastructure/management/ReconfigurationEventHandler.java]: These should be helper methods. Otherwise this logic gets strewn everywhere. It should be only in one place.

File: infrastructure/src/main/java/org/corfudb/infrastructure/management/ReconfigurationEventHandler.java [hunk 7]
```diff
@@ -102,4 +116,32 @@ public static boolean handleHealing(@Nonnull CorfuRuntime runtime,
...
+        // Fetching the first stripe for determinism.
+        List<String> firstStripeLogServers = lastSegment.getStripes().get(0).getLogServers();
+        runtime.getManagementView().mergeSegments(
+                // Last log unit in the stripe.
+                firstStripeLogServers.get(firstStripeLogServers.size() - 1),
```
Comment (medhavidhawan) [inline infrastructure/src/main/java/org/corfudb/infrastructure/management/ReconfigurationEventHandler.java]: This should not be calculated here but should be in helper. Also if the layout changes between first and second try then are we just doomed for that run ? If so why can't we do better.

File: infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/RestoreRedundancyMergeSegments.java [hunk 8]
```diff
@@ -0,0 +1,54 @@
...
+    @Override
+    public void impl(@Nonnull CorfuRuntime runtime) throws OutrankedException,
+            ExecutionException,
+            InterruptedException {
+
+        Layout layout;
+
+        // Catchup all servers across all segments.
+        do {
+            runtime.invalidateLayout();
```
Comment (medhavidhawan) [inline infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/RestoreRedundancyMergeSegments.java]: what is this line for ?

File: infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/RestoreRedundancyMergeSegments.java [hunk 9]
```diff
@@ -0,0 +1,54 @@
...
+            layout = runtime.getLayoutView().getLayout();
+
+            // Currently the state is transferred for the complete segment.
+            // TODO: Add stripe specific transfer granularity for optimization.
+            // Get the set of servers present in the second segment but not in the first
+            // segment.
+            Set<String> lowRedundancyServers = Sets.difference(
```
Comment (medhavidhawan) [inline infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/RestoreRedundancyMergeSegments.java]: What is this trying to do ?

File: infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/RestoreRedundancyMergeSegments.java [hunk 10]
```diff
@@ -0,0 +1,54 @@
...
+                    layout.getSegments().get(1).getAllLogServers(),
```
Comment (medhavidhawan) [inline infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/RestoreRedundancyMergeSegments.java]: please provide more descriptive helper methods.

File: runtime/src/main/java/org/corfudb/runtime/view/workflows/MergeSegments.java [hunk 11]
```diff
@@ -0,0 +1,51 @@
...
+    protected UUID sendRequest(@NonNull ManagementClient managementClient) throws TimeoutException {
+        CreateWorkflowResponse resp = managementClient.mergeSegments(nodeForWorkflow);
+        log.info("sendRequest: requested to heal {} on orchestrator {}:{}",
+                nodeForWorkflow, managementClient.getRouter().getHost(),
+                managementClient.getRouter().getPort());
+        return resp.getWorkflowId();
+    }
+
+    @Override
+    protected boolean verifyRequest(@NonNull Layout layout) {
```
Comment (medhavidhawan) [inline runtime/src/main/java/org/corfudb/runtime/view/workflows/MergeSegments.java]: Needs a comment.

File: test/src/test/java/org/corfudb/integration/AbstractIT.java [hunk 12]
```diff
@@ -166,6 +170,28 @@ public void restartServer(CorfuRuntime corfuRuntime, String endpoint) {
...
+     * satisfy the expected verifier.
+     *
+     * @param verifier     Layout predicate to test the refreshed layout.
+     * @param corfuRuntime corfu runtime.
+     */
+    public static void waitForLayoutChange(Predicate<Layout> verifier, CorfuRuntime corfuRuntime) {
+        corfuRuntime.invalidateLayout();
+        Layout refreshedLayout = corfuRuntime.getLayoutView().getLayout();
+
+        for (int i = 0; i < PARAMETERS.NUM_ITERATIONS_MODERATE; i++) {
```
Comment (medhavidhawan) [inline test/src/test/java/org/corfudb/integration/AbstractIT.java]: I do not like these sleeps. Why do we not use latches or something more deterministic.

Comment (medhavidhawan) [reply test/src/test/java/org/corfudb/integration/AbstractIT.java]: If it is stuck the test will timeout and we will know something is wrong.

File: infrastructure/src/main/java/org/corfudb/infrastructure/RemoteMonitoringService.java [hunk 13]
```diff
@@ -360,12 +368,36 @@ private synchronized void runDetectionTasks() {
...
+
             handleSequencer(serverContext.copyManagementLayout());
 
             return DetectorTask.COMPLETED;
         }, failureDetectorWorker);
     }
 
+
+    /**
+     * Spawns a new task to merge segments if no task in progress.
```
[the remark this answers is not in the document]
Comment (zalokhan) [reply infrastructure/src/main/java/org/corfudb/infrastructure/RemoteMonitoringService.java]: Done.

File: infrastructure/src/main/java/org/corfudb/infrastructure/RemoteMonitoringService.java (hunk 2 above)
[the remark this answers is not in the document]
Comment (zalokhan) [reply infrastructure/src/main/java/org/corfudb/infrastructure/RemoteMonitoringService.java]: Done.

File: infrastructure/src/main/java/org/corfudb/infrastructure/management/ReconfigurationEventHandler.java (hunk 6 above)
[the remark this answers is not in the document]
Comment (zalokhan) [reply infrastructure/src/main/java/org/corfudb/infrastructure/management/ReconfigurationEventHandler.java]: Done.

File: infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/StateTransfer.java [hunk 14]
```diff
@@ -0,0 +1,117 @@
...
+import org.corfudb.runtime.CorfuRuntime;
+import org.corfudb.runtime.view.Layout;
+import org.corfudb.util.CFUtils;
+
+/**
+ * State transfer utility.
+ * Created by zlokhandwala on 2019-02-06.
+ */
+@Slf4j
+public class StateTransfer {
```
[the remark this answers is not in the document]
Comment (zalokhan) [reply infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/StateTransfer.java]: State transfer is more of a static utility and `restoreRedundnacyMergeSegments` is an Action. That's why I have kept them both separate. Also, `restoreRedundancy` in `AddNodeWorkflow` also uses `stateTransfer` and hence needs to be kept separate. Let me know your thoughts on this.

File: test/src/test/java/org/corfudb/integration/AbstractIT.java [hunk 15]
```diff
@@ -166,6 +170,28 @@ public void restartServer(CorfuRuntime corfuRuntime, String endpoint) {
...
     }
 
+    /**
+     * Refreshes the layout and waits for a limited time for the refreshed layout to
+     * satisfy the expected verifier.
+     *
+     * @param verifier     Layout predicate to test the refreshed layout.
+     * @param corfuRuntime corfu runtime.
+     */
+    public static void waitForLayoutChange(Predicate<Layout> verifier, CorfuRuntime corfuRuntime) {
```
[the remark this answers is not in the document]
Comment (zalokhan) [reply test/src/test/java/org/corfudb/integration/AbstractIT.java]: AbstractCorfuTest is more of a test runner. This utility method does not belong there. I'll create a utility class to avoid duplication.

File: infrastructure/src/main/java/org/corfudb/infrastructure/RemoteMonitoringService.java [hunk 16]
```diff
@@ -360,12 +368,36 @@ private synchronized void runDetectionTasks() {
...
+     * @return Detector task.
+     */
+    private DetectorTask mergeSplitSegments() {
+        Layout layout = serverContext.copyManagementLayout();
+
+        if (layout.getSegments().size() == 1 || !mergeSegmentsTask.isDone()) {
+            return DetectorTask.SKIPPED;
+        }
+
+        mergeSegmentsTask = CompletableFuture.supplyAsync(() -> {
```
[the remark this answers is not in the document]
Comment (zalokhan) [reply infrastructure/src/main/java/org/corfudb/infrastructure/RemoteMonitoringService.java]: Sorry I meant to run this on `failureDetectorWorkers` pool. Have made the change.

File: infrastructure/src/main/java/org/corfudb/infrastructure/management/ReconfigurationEventHandler.java (hunk 4 above)
Comment (zalokhan) [reply infrastructure/src/main/java/org/corfudb/infrastructure/management/ReconfigurationEventHandler.java]: This is logged in the consumers of this method.

File: infrastructure/src/main/java/org/corfudb/infrastructure/management/ReconfigurationEventHandler.java (hunk 5 above)
Comment (zalokhan) [reply infrastructure/src/main/java/org/corfudb/infrastructure/management/ReconfigurationEventHandler.java]: Done.

File: runtime/src/main/java/org/corfudb/runtime/view/workflows/MergeSegments.java (hunk 11 above)
Comment (zalokhan) [reply runtime/src/main/java/org/corfudb/runtime/view/workflows/MergeSegments.java]: Done.

File: infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/StateTransfer.java (hunk 14 above)
[the remark this answers is not in the document]
Comment (WenbinZhu) [reply infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/StateTransfer.java]: I'm ok with it.

File: infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/RestoreRedundancyMergeSegments.java (hunk 10 above)
Comment (zalokhan) [reply infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/RestoreRedundancyMergeSegments.java]: Done.

File: infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/RestoreRedundancyMergeSegments.java (hunk 9 above)
Comment (zalokhan) [reply infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/RestoreRedundancyMergeSegments.java]: This finds the difference in the 2 sets: Segment 1 and Segment 0 to find out nodes present in 1 and not in 0. These nodes need state transfer before the segments can be merged.

File: infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/RestoreRedundancyMergeSegments.java (hunk 8 above)
Comment (zalokhan) [reply infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/RestoreRedundancyMergeSegments.java]: Needed for layout refresh before this Action is invoked. Added comments.

File: infrastructure/src/main/java/org/corfudb/infrastructure/management/ReconfigurationEventHandler.java [hunk 17]
```diff
@@ -102,4 +116,32 @@ public static boolean handleHealing(@Nonnull CorfuRuntime runtime,
...
+    /**
+     * Launches a workflow to restore redundancy and merge all segments.
+     *
+     * @param runtime Connected corfu runtime instance.
+     * @param layout  Latest known layout.
+     */
+    public static void handleMergeSegments(@Nonnull CorfuRuntime runtime, @Nonnull Layout layout) {
+
+        Duration workflowTimeout = getReasonableWorkflowTimeout(runtime);
+        log.info("triggerMergeSegments: Workflow to merge segments for layout {} timeout set to {} ms",
```
Comment (WenbinZhu) [inline infrastructure/src/main/java/org/corfudb/infrastructure/management/ReconfigurationEventHandler.java]: triggerMergeSegments -> handleMergeSegments

File: infrastructure/src/main/java/org/corfudb/infrastructure/management/ReconfigurationEventHandler.java (hunk 6 above)
Comment (zalokhan) [reply infrastructure/src/main/java/org/corfudb/infrastructure/management/ReconfigurationEventHandler.java]: Done.

File: infrastructure/src/main/java/org/corfudb/infrastructure/RemoteMonitoringService.java (hunk 1 above)
Comment (zalokhan) [reply infrastructure/src/main/java/org/corfudb/infrastructure/RemoteMonitoringService.java]: /**
Number of workers for failure detector. Three workers used for the following tasks:
- failure/healing detection
- bootstrap sequencer
- merge segments

File: infrastructure/src/main/java/org/corfudb/infrastructure/management/ReconfigurationEventHandler.java (hunk 17 above)
Comment (zalokhan) [reply infrastructure/src/main/java/org/corfudb/infrastructure/management/ReconfigurationEventHandler.java]: Done.

**Comment by zalokhan** [comment]
@medhavidhawan @WenbinZhu Addressed all comments. Can you please review.

**Comment by WenbinZhu** [comment]
@medhavidhawan @zalokhan I was just thinking if we can make mergeSegment workflow no retry at all, since anyway we run this task every one second together with failure detection task. What do you think?

**Comment by zalokhan** [comment]
I think it's helpful to have the same number of retries as heal node = 3 retries.
This is just to avoid trivial exceptions like WrongEpochExceptions which might just delay the merge segments by a couple of polling cycles.

File: infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/RestoreRedundancyMergeSegments.java [hunk 18]
```diff
@@ -0,0 +1,73 @@
...
+        // Catchup all servers across all segments.
+        while (layout.getSegments().size() > 1) {
+
+            Set<String> lowRedundancyServers = getNodesWithReducedRedundancy(layout, 1);
+
+            // Currently the state is transferred for the complete segment.
+            // TODO: Add stripe specific transfer granularity for optimization.
+            // Transfer the replicated segment to the difference set calculated above.
+            StateTransfer.transfer(layout, lowRedundancyServers, runtime, layout.getSegments().get(0));
+
```
Comment (xnull) [inline infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/RestoreRedundancyMergeSegments.java]: can you please provide `getFirstSegment()` method instead of `getSegments().get(0)`

File: infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/RestoreRedundancyMergeSegments.java [hunk 19]
```diff
@@ -0,0 +1,73 @@
...
+    }
+
+    @Override
+    public void impl(@Nonnull CorfuRuntime runtime) throws OutrankedException,
+            ExecutionException,
+            InterruptedException {
+
+        // Refresh layout.
+        runtime.invalidateLayout();
+        Layout layout = runtime.getLayoutView().getLayout();
```
[the remark this answers is not in the document]
Comment (zalokhan) [reply infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/RestoreRedundancyMergeSegments.java]: Yes, that's my next step. But not in this patch. I'll defer it to the next PR.

File: infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/RestoreRedundancyMergeSegments.java [hunk 20]
```diff
@@ -0,0 +1,73 @@
...
+
+        // Catchup all servers across all segments.
+        while (layout.getSegments().size() > 1) {
+
+            Set<String> lowRedundancyServers = getNodesWithReducedRedundancy(layout, 1);
+
```
[the remark this answers is not in the document]
Comment (zalokhan) [reply infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/RestoreRedundancyMergeSegments.java]: Added comments.

File: infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/StateTransfer.java [hunk 21]
```diff
@@ -0,0 +1,117 @@
...
+        }
+
+        // State transfer should start from segment start address or trim mark whichever is lower.
+        long segmentStart = Math.max(trimMark, segment.getStart());
+
+        for (long chunkStart = segmentStart; chunkStart < segment.getEnd()
+                ; chunkStart = chunkStart + batchSize) {
+            long chunkEnd = Math.min((chunkStart + batchSize - 1), segment.getEnd() - 1);
+
+            long ts1 = System.currentTimeMillis();
```
Comment (xnull) [inline infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/StateTransfer.java]: let's replace this by metrics, let's use metrics if we need to measure performance here

File: infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/StateTransfer.java [hunk 22]
```diff
@@ -0,0 +1,117 @@
...
+                            Range.closed(chunkStart, chunkEnd),
+                            DiscreteDomain.longs()));
+
+            long ts2 = System.currentTimeMillis();
+
+            log.info("stateTransfer: read {}-{} in {} ms", chunkStart, chunkEnd, (ts2 - ts1));
+
+            List<LogData> entries = new ArrayList<>();
+            for (long x = chunkStart; x <= chunkEnd; x++) {
+                if (dataMap.get(x) == null) {
```
Comment (xnull) [inline infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/StateTransfer.java]: containsKey

File: infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/StateTransfer.java [hunk 23]
```diff
@@ -0,0 +1,117 @@
...
+                    log.error("Missing address {} in range {}-{}", x, chunkStart, chunkEnd);
+                    throw new IllegalStateException("Missing address");
+                }
+                entries.add((LogData) dataMap.get(x));
```
Comment (xnull) [inline infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/StateTransfer.java]: why class cast? can we get rid of casting?

File: infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/StateTransfer.java [hunk 24]
```diff
@@ -0,0 +1,117 @@
...
+            }
+
+            for (String endpoint : endpoints) {
+                // Write segment chunk to the new logunit
+                ts1 = System.currentTimeMillis();
+                boolean transferSuccess = runtime.getLayoutView().getRuntimeLayout(layout)
+                        .getLogUnitClient(endpoint)
+                        .writeRange(entries).get();
+                ts2 = System.currentTimeMillis();
```
Comment (xnull) [inline infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/StateTransfer.java]: can we return completablefuture instead of blocking current thread and waiting for result?

File: infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/workflows/MergeSegmentsWorkflow.java [hunk 25]
```diff
@@ -0,0 +1,52 @@
...
+public class MergeSegmentsWorkflow implements IWorkflow {
+
+
+    private final MergeSegmentsRequest request;
+
+    @Getter
+    final UUID id;
+
+    @Getter
+    List<Action> actions;
```
Comment (xnull) [inline infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/workflows/MergeSegmentsWorkflow.java]: private final? Why you need getter?

File: infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/workflows/MergeSegmentsWorkflow.java [hunk 26]
```diff
@@ -0,0 +1,52 @@
...
+ * Created by Zeeshan on 2019-02-06.
+ */
+@Slf4j
+public class MergeSegmentsWorkflow implements IWorkflow {
+
+
+    private final MergeSegmentsRequest request;
+
+    @Getter
+    final UUID id;
```
Comment (xnull) [inline infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/workflows/MergeSegmentsWorkflow.java]: private

File: runtime/src/main/java/org/corfudb/protocols/wireprotocol/orchestrator/MergeSegmentsRequest.java [hunk 27]
```diff
@@ -0,0 +1,38 @@
...
+ * An orchestrator request to merge all segments in the cluster.
+ * Created by Zeeshan on 2019-02-06.
+ */
+public class MergeSegmentsRequest implements CreateRequest {
+
+    /**
+     * Endpoint to restore redundancy to. Data needs to be transferred to this node.
+     */
+    @Getter
+    public String endpoint;
```
Comment (xnull) [inline runtime/src/main/java/org/corfudb/protocols/wireprotocol/orchestrator/MergeSegmentsRequest.java]: why public? whu not final?

File: infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/RestoreRedundancyMergeSegments.java (hunk 18 above)
Comment (zalokhan) [reply infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/RestoreRedundancyMergeSegments.java]: Done.

File: infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/StateTransfer.java [hunk 28]
```diff
@@ -0,0 +1,117 @@
...
+        // Send the trimMark to the new/healing nodes.
+        // If this times out or fails, the Action performing the stateTransfer fails and retries.
+        for (String endpoint : endpoints) {
+            // TrimMark is the first address present on the log unit server.
+            // Perform the prefix trim on the preceding address = (trimMark - 1).
+            // Since the LU will reject trim decisions made from older epochs, we
+            // need to adjust the new trim mark to have the new layout's epoch.
+            Token prefixToken = new Token(layout.getEpoch(), trimMark - 1);
+            CFUtils.getUninterruptibly(runtime.getLayoutView().getRuntimeLayout(layout)
+                    .getLogUnitClient(endpoint)
```
Comment (xnull) [inline infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/StateTransfer.java]: Why not just return completablefuture? Why do we need to block current thread?

File: runtime/src/main/java/org/corfudb/runtime/view/Layout.java [hunk 29]
```diff
@@ -282,6 +282,19 @@ public LayoutSegment getLatestSegment() {
...
+     * Get the last node in the last segment.
+     *
+     * @return Returns the last node in the last segment.
+     */
+    public String getLastAddedNodeInLastSegment() {
+
+        // Fetching the latest segment. Note: This is the unbounded segment with ongoing writes.
+        // Returning the last node in the first stripe for determinism.
+        List<String> firstStripeLogServers = getLatestSegment().getStripes().get(0).getLogServers();
+        return firstStripeLogServers.get(firstStripeLogServers.size() - 1);
```
[the remark this answers is not in the document]
Comment (zalokhan) [reply runtime/src/main/java/org/corfudb/runtime/view/Layout.java]: Done.

File: runtime/src/main/java/org/corfudb/runtime/view/workflows/MergeSegments.java [hunk 30]
```diff
@@ -0,0 +1,73 @@
...
+     * Creates and sends the workflow request to restore redundancy and merge the segments.
+     *
+     * @param managementClient Management Client to send the orchestrator request.
+     * @return Workflow ID.
+     * @throws TimeoutException thrown is orchestrator request was not acknowledged within the RPC timeout.
+     */
+    @Override
+    protected UUID sendRequest(@NonNull ManagementClient managementClient) throws TimeoutException {
+        CreateWorkflowResponse resp = managementClient.mergeSegments(nodeForWorkflow);
+        log.info("sendRequest: requested to heal {} on orchestrator {}:{}",
```
Comment (annym) [inline runtime/src/main/java/org/corfudb/runtime/view/workflows/MergeSegments.java]: is the right word here to heal? isn't it to restore redundancy and merge?

File: runtime/src/main/java/org/corfudb/protocols/wireprotocol/orchestrator/MergeSegmentsRequest.java [hunk 31]
```diff
@@ -0,0 +1,38 @@
...
+
+import java.nio.charset.StandardCharsets;
+
+import lombok.Getter;
+
+/**
+ * An orchestrator request to merge all segments in the cluster.
+ * Created by Zeeshan on 2019-02-06.
+ */
+public class MergeSegmentsRequest implements CreateRequest {
```
Comment (annym) [inline runtime/src/main/java/org/corfudb/protocols/wireprotocol/orchestrator/MergeSegmentsRequest.java]: It's kind of confusing MergeSegmentsRequest from MergeSegments (that implements WorkflowRequest) is one for redundancy and merge and the other only for merge? why two requests? I thought we only needed the workflow request, can we make this cleaner? or can you please explain this. thanks

File: infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/workflows/AddNodeWorkflow.java [hunk 32]
```diff
@@ -236,7 +154,7 @@ public void impl(@Nonnull CorfuRuntime runtime) throws OutrankedException,
                 // The new server is already a part of the last segment. This is based on an
                 // assumption that the newly added node is not removed from the layout.
                 for (int i = 0; i < newLayout.getSegments().size() - 1; i++) {
-                    stateTransfer(Collections.singleton(request.getEndpoint()),
+                    StateTransfer.transfer(newLayout, Collections.singleton(request.getEndpoint()),
```
[the remark this answers is not in the document]
Comment (zalokhan) [reply infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/workflows/AddNodeWorkflow.java]: Done.

File: infrastructure/src/main/java/org/corfudb/infrastructure/RemoteMonitoringService.java [hunk 33]
```diff
@@ -360,12 +368,41 @@ private synchronized void runDetectionTasks() {
                 return DetectorTask.COMPLETED;
             }
 
+            // Restores redundancy and merges multiple segments if present.
+            mergeSplitSegments();
```
[the remark this answers is not in the document]
Comment (zalokhan) [reply infrastructure/src/main/java/org/corfudb/infrastructure/RemoteMonitoringService.java]: Done.

File: infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/StateTransfer.java (hunk 21 above)
Comment (xnull) [reply infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/StateTransfer.java]: Why only for datapath? We need metrics for everything. This is a new/updated functional, and we don't use metrics, we ignore it. I believe that's not right

File: infrastructure/src/main/java/org/corfudb/infrastructure/RemoteMonitoringService.java [hunk 34]
```diff
@@ -360,12 +368,41 @@ private synchronized void runDetectionTasks() {
...
+
+        if (layout.getSegments().size() == 1) {
+            log.debug("No segments to merge. Skipping step.");
+            return DetectorTask.SKIPPED;
+        } else if (!mergeSegmentsTask.isDone()) {
+            log.debug("Merge segments task already in progress. Skipping spawning another task.");
+            return DetectorTask.SKIPPED;
+        }
+
+        log.debug("Multiple segments present. Spawning task to merge segments.");
```
[the remark this answers is not in the document]
Comment (zalokhan) [reply infrastructure/src/main/java/org/corfudb/infrastructure/RemoteMonitoringService.java]: Done.

File: infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/StateTransfer.java (hunk 24 above)
Comment (xnull) [reply infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/actions/StateTransfer.java]: So, if you don't start using it properly, you will always use `get()`, why not to start using it properly right now?
You can easily measure performance for this, just execute `whenComplete()` and measure the time taken for this operation.

File: infrastructure/src/main/java/org/corfudb/infrastructure/management/ReconfigurationEventHandler.java [hunk 35]
```diff
@@ -102,4 +115,42 @@ public static boolean handleHealing(@Nonnull CorfuRuntime runtime,
             return false;
         }
     }
+
+    /**
+     * Launches a workflow to restore redundancy and merge all segments.
+     * This method sends an orchestrator request to restore redundancy and merge all segments. This task is run
+     * asynchronously at regular intervals by the failure detector. This is a blocking task and will complete if
```
[the remark this answers is not in the document]
Comment (zalokhan) [reply infrastructure/src/main/java/org/corfudb/infrastructure/management/ReconfigurationEventHandler.java]: Runs in the presence of multiple segments. I have updated the comment to reflect this.

File: infrastructure/src/main/java/org/corfudb/infrastructure/management/ReconfigurationEventHandler.java [hunk 36]
```diff
@@ -56,6 +57,29 @@ public static boolean handleFailure(@Nonnull IReconfigurationHandlerPolicy failu
...
+        Token trimMark = runtime.getAddressSpaceView().getTrimMark();
+        long tail = runtime.getAddressSpaceView().getAllTails().getLogTail();
+
+        long rangeToReplicate = tail - trimMark.getSequence();
+        // Since the orchestrator client and the fault detector client use
+        // the same configuration its reasonable to use these arguments.
+        // TODO(Maithem): AddNode should use a similar mechanism to set the timeout
+        long numSections = rangeToReplicate / runtime.getParameters().getBulkReadSize();
+        long rpcTimeout = (long) (runtime.getParameters().getRequestTimeout().toMillis() * 1.5);
+        long timeoutInMs = Math.max(DEFAULT_HEAL_TIMEOUT.toMillis(), numSections * rpcTimeout);
```
[the remark this answers is not in the document]
Comment (xnull) [reply infrastructure/src/main/java/org/corfudb/infrastructure/management/ReconfigurationEventHandler.java]: Let's use Duration instead of long

[the remark this answers is not in the document]
Comment (zalokhan) [reply infrastructure/src/main/java/org/corfudb/infrastructure/management/ReconfigurationEventHandler.java]: It's a multiplicative factor added to estimate the timeout calculated using the RPC timeout, bulk size and the number of entries. I've added comments and made it a constant.

File: infrastructure/src/main/java/org/corfudb/infrastructure/management/ReconfigurationEventHandler.java [hunk 37]
```diff
@@ -102,4 +115,42 @@ public static boolean handleHealing(@Nonnull CorfuRuntime runtime,
...
+    public static boolean handleMergeSegments(@Nonnull CorfuRuntime runtime, @Nonnull Layout layout) {
+
+        log.info("Handling split segments");
+
+        try {
+            Duration workflowTimeout = getStateTransferTimeoutEstimate(runtime);
+            log.info("handleMergeSegments: Workflow to merge segments for layout {} timeout set to {} ms",
+                    layout, workflowTimeout);
+
+            final Duration retryQueryTimeout = Duration.ofSeconds(1);
```
[the remark this answers is not in the document]
Comment (zalokhan) [reply infrastructure/src/main/java/org/corfudb/infrastructure/management/ReconfigurationEventHandler.java]: Done.

File: runtime/src/main/java/org/corfudb/protocols/wireprotocol/orchestrator/MergeSegmentsRequest.java (hunk 31 above)
Comment (zalokhan) [reply runtime/src/main/java/org/corfudb/protocols/wireprotocol/orchestrator/MergeSegmentsRequest.java]: MergeSegments is the abstraction which actually sends the message to the orchestrator.
While the MergeSegmentsRequest is just the request message which gets sent.

File: runtime/src/main/java/org/corfudb/runtime/view/workflows/MergeSegments.java (hunk 30 above)
Comment (zalokhan) [reply runtime/src/main/java/org/corfudb/runtime/view/workflows/MergeSegments.java]: fixed.

File: infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/Orchestrator.java [hunk 38]
```diff
@@ -124,6 +126,10 @@ public void handle(@Nonnull CorfuPayloadMsg<OrchestratorMsg> msg,
                 workflow = new ForceRemoveWorkflow((ForceRemoveNodeRequest) orchReq.getRequest());
                 dispatch(workflow, msg, ctx, r);
                 break;
+            case MERGE_SEGMENTS:
+                workflow = new MergeSegmentsWorkflow((MergeSegmentsRequest) orchReq.getRequest());
```
[the remark this answers is not in the document]
Comment (zalokhan) [reply infrastructure/src/main/java/org/corfudb/infrastructure/orchestrator/Orchestrator.java]: fixed.

File: infrastructure/src/main/java/org/corfudb/infrastructure/management/ReconfigurationEventHandler.java [hunk 39]
```diff
@@ -56,6 +57,29 @@ public static boolean handleFailure(@Nonnull IReconfigurationHandlerPolicy failu
...
+
+        // Try to estimate a reasonable timeout to rebuild the logging unit
+        Token trimMark = runtime.getAddressSpaceView().getTrimMark();
+        long tail = runtime.getAddressSpaceView().getAllTails().getLogTail();
+
+        long rangeToReplicate = tail - trimMark.getSequence();
+        // Since the orchestrator client and the fault detector client use
+        // the same configuration its reasonable to use these arguments.
+        // TODO(Maithem): AddNode should use a similar mechanism to set the timeout
+        long numSections = rangeToReplicate / runtime.getParameters().getBulkReadSize();
```
[the remark this answers is not in the document]
Comment (zalokhan) [reply infrastructure/src/main/java/org/corfudb/infrastructure/management/ReconfigurationEventHandler.java]: I agree. We need to dynamically resize the bulk size. We already log the time required to transfer each chunk in the state transfer. I'll add a TODO as you suggested to resize the bulk size depending on the retries or timeouts.

**Comment by zalokhan** [comment]
No, to prevent them from getting stuck, an extra thread is added. They shouldn't get stuck even if something gets delayed.
