### PR TITLE
Fix SystemDownHandler crashing ScheduledExecutorService

### LINKED ISSUE #1479: ScheduledExecutorServices don't schedule when threads crash exceptionally.
## Overview
ScheduledExecutorServices don't schedule when threads crash exceptionally.
ManagementService and SyncTrimTask die in case the runtime executes the systemDownHandler.

### PR DESCRIPTION
**Pull request by zalokhan**
## Overview

Description:

Why should this be merged: 

Related issue(s) (if applicable): Fixes #1479 

## Checklist (Definition of Done):

- [x] There are no TODOs left in the code
- [x] [Coding conventions](https://github.com/CorfuDB/CorfuDB/wiki/Corfu-Style-Guidelines) (e.g. for logging, unit tests) have been followed
- [x] Change is covered by automated tests
- [x] Public API has Javadoc

### CODE REVIEW

File: infrastructure/src/main/java/org/corfudb/infrastructure/ManagementAgent.java [hunk 1]
```diff
@@ -385,36 +385,43 @@ private boolean runRecoveryReconfiguration() {
...
+            if (layout == null) {
+                return;
+            }
+
+            // Build and replace existing locally stored nodeMetrics
+            SequencerMetrics sequencerMetrics;
+            // This is an optimization. If this node is not the primary sequencer for the current
+            // layout, there is no reason to request metrics from this sequencer.
+            if (layout.getSequencers().get(0).equals(getLocalEndpoint())) {
+                try {
```
Comment (corfu-repo) [inline infrastructure/src/main/java/org/corfudb/infrastructure/ManagementAgent.java]: MAJOR Extract this nested try block into a separate method. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1141)

Comment (medhavidhawan) [reply infrastructure/src/main/java/org/corfudb/infrastructure/ManagementAgent.java]: maybe we can refactor according to the automated suggestion in this case.

File: infrastructure/src/main/java/org/corfudb/infrastructure/ManagementAgent.java [hunk 2]
```diff
@@ -385,36 +385,43 @@ private boolean runRecoveryReconfiguration() {
...
-            sequencerMetrics = new SequencerMetrics(SequencerStatus.UNKNOWN);
-        }
 
-        localServerMetrics =
-                new ServerMetrics(NodeLocator.parseString(getLocalEndpoint()), sequencerMetrics);
+            localServerMetrics =
+                    new ServerMetrics(NodeLocator.parseString(getLocalEndpoint()),
+                            sequencerMetrics);
+
+        } catch (Exception e) {
```
Comment (medhavidhawan) [inline infrastructure/src/main/java/org/corfudb/infrastructure/ManagementAgent.java]: should this be a method wrapper utility so that you do not have to do it in multiple places.

File: infrastructure/src/main/java/org/corfudb/infrastructure/ManagementAgent.java (hunk 1 above)
Comment (zalokhan) [reply infrastructure/src/main/java/org/corfudb/infrastructure/ManagementAgent.java]: Done.

File: infrastructure/src/main/java/org/corfudb/infrastructure/ManagementAgent.java (hunk 2 above)
Comment (zalokhan) [reply infrastructure/src/main/java/org/corfudb/infrastructure/ManagementAgent.java]: Done.

File: runtime/src/main/java/org/corfudb/util/LambdaUtils.java [hunk 3]
```diff
@@ -154,4 +157,18 @@ public static Object executeUnknownLambda(Object unknownLambda, Object... argume
...
         Object resolve(T resolver, Object[] args);
     }
+
+    /**
+     * Suppresses all exceptions. This is used for scheduling tasks to ScheduledExecutorService.
+     * ScheduledExecutorService crashes in case a scheduled thread throws an Exception.
+     *
+     * @param runnable Task whose exceptions are to be suppressed.
+     */
+    public static void suppressExceptions(Runnable runnable) {
```
Comment (medhavidhawan) [inline runtime/src/main/java/org/corfudb/util/LambdaUtils.java]: suppress might be a strong word for this. I do not have good suggestions but something like runNoThrow might be more appropriate.

File: infrastructure/src/main/java/org/corfudb/infrastructure/ManagementAgent.java [hunk 4]
```diff
@@ -412,9 +405,29 @@ private void updateLocalMetrics() {
...
+
+    /**
+     * Task to collect local node metrics.
+     * This task collects the following:
+     * Boolean Status of layout, sequencer and logunit servers.
+     * These metrics are then composed into ServerMetrics model and stored locally.
+     */
+    private void updateLocalMetrics() {
+
+        suppressExceptions(() -> {
```
Comment (medhavidhawan) [inline infrastructure/src/main/java/org/corfudb/infrastructure/ManagementAgent.java]: i do not think wrapping should be here . It should be at scheduling level. The problem is that scheduler is finicky.
