### PR TITLE
Fix partially sealed cluster and close handlers.

### LINKED ISSUE #1478: Partially sealed degraded cluster causes liveness issue.
## Overview
A partially sealed degraded cluster never heals itself and fills up the layout slot causing a liveness issue.

### PR DESCRIPTION
**Pull request by zalokhan**
## Overview

Description: 
Fix partially sealed cluster by filling the epoch slot.
Close unused netty pipeline duplex handlers which timeout every 30 seconds even if the channel is used.

Why should this be merged: Resolves liveness issue.

Related issue(s) (if applicable): Fixes #1478 

## Checklist (Definition of Done):

- [x] There are no TODOs left in the code
- [x] [Coding conventions](https://github.com/CorfuDB/CorfuDB/wiki/Corfu-Style-Guidelines) (e.g. for logging, unit tests) have been followed
- [x] Change is covered by automated tests
- [x] Public API has Javadoc

### CODE REVIEW

File: test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java [hunk 1]
```diff
@@ -1914,4 +1914,42 @@ public void failoverSeqDoesNotRegressTokenValue() throws Exception {
         assertThat(corfuRuntime.getSequencerView().query().getTokenValue())
                 .isEqualTo(expectedTokenValue);
     }
+
+    /**
+     * Tests that a degraded cluster heals a partially sealed cluster.
```
Comment (medhavidhawan) [inline test/src/test/java/org/corfudb/runtime/view/ManagementViewTest.java]: what is the partially sealed part. The comments are not descriptive enough

File: infrastructure/src/main/java/org/corfudb/infrastructure/ManagementAgent.java [hunk 2]
```diff
@@ -576,17 +577,22 @@ private void runFailureDetectorTask() {
...
-     * slot by proposing a new layout.
+     * All active Layout servers have been sealed but there is no client to take this forward and
+     * fill the slot by proposing a new layout.
      * In this case we can pass an empty set to propose the same layout again and fill the layout
      * slot to un-block the data plane operations.
      *
      * @param pollReport Report from the polling task
      * @return True if latest layout slot is vacant. Else False.
      */
     private boolean isCurrentLayoutSlotUnFilled(PollReport pollReport) {
```
Comment (medhavidhawan) [inline infrastructure/src/main/java/org/corfudb/infrastructure/ManagementAgent.java]: the code where this method is called probably needs some refactoring as it is hard to figure out what is going on in the code.

File: infrastructure/src/main/java/org/corfudb/infrastructure/ServerHandshakeHandler.java [hunk 3]
```diff
@@ -76,7 +76,9 @@ public void channelRead(ChannelHandlerContext ctx, Object m) throws Exception {
             handshake = (CorfuPayloadMsg<HandshakeMsg>) m;
             log.debug("channelRead: Handshake Message received. Removing {} from pipeline.",
                     READ_TIMEOUT_HANDLER);
-            ctx.pipeline().remove(READ_TIMEOUT_HANDLER);
+            // Remove the handler from the pipeline. Also remove the reference of the context from
+            // the handler so that it does not disconnect the channel.
+            ctx.pipeline().remove(READ_TIMEOUT_HANDLER).handlerRemoved(ctx);;
```
Comment (corfu-repo) [inline infrastructure/src/main/java/org/corfudb/infrastructure/ServerHandshakeHandler.java]: MINOR Remove this empty statement. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AEmptyStatementUsageCheck)

**Comment by corfu-repo** [comment]
SonarQube analysis reported 1 issue
* ![MINOR][MINOR] 1 minor

Watch the comments in this conversation to review them.

[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by zalokhan** [comment]
This fails the pre-checkin liveness test. The failure is orthogonal to this PR and I am currently investigating the issue. Pushing this in.
