### PR TITLE
Invalidate Layout on SystemDownHandler trigger

### LINKED ISSUE #1466: Client cannot reconnect after firing systemDownHandler
## Overview

The CorfuRuntime cannot reconnect once it has invoked the systemDownHandler.
This is because the layoutCompletableFuture is stuck with the exceptionally completed layout.

Needs to be fixed in 0.2.1 and 0.2.2

### PR DESCRIPTION
**Pull request by zalokhan**
## Overview

Description:
Invalidate layout when invoking systemDownHandler. Else the layout completable future is stuck with the systemDownHandlerException forever.

Why should this be merged: The layout completable future is stuck with the systemDownHandlerException forever.

Related issue(s) (if applicable): Fixes #1466 

## Checklist (Definition of Done):

- [x] There are no TODOs left in the code
- [x] [Coding conventions](https://github.com/CorfuDB/CorfuDB/wiki/Corfu-Style-Guidelines) (e.g. for logging, unit tests) have been followed
- [x] Change is covered by automated tests
- [x] Public API has Javadoc

### CODE REVIEW

File: runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java [hunk 1]
```diff
@@ -696,7 +696,17 @@ public synchronized void invalidateLayout() {
...
         }
-        layout = fetchLayout(CFUtils.getUninterruptibly(layout).getLayoutServers());
+        List<String> lastKnownLayoutServers = layoutServers;
+        try {
+            if (layout != null) {
+                // Layout fetch can result in an exception if the systemDownHandler was invoked and
+                // the completable future was completed exceptionally.
+                lastKnownLayoutServers = CFUtils.getUninterruptibly(layout).getLayoutServers();
+            }
+        } catch (Throwable th) {
```
Comment (corfu-repo) [inline runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java]: MAJOR Catch Exception instead of Throwable. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1181)

File: runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java [hunk 2]
```diff
@@ -753,8 +763,19 @@ private void pruneRemovedRouters(@Nonnull Layout layout) {
      */
     private CompletableFuture<Layout> fetchLayout(List<String> layoutServers) {
 
+        // Layout fetch can result in an exception if the systemDownHandler was invoked and the
+        // completable future was completed exceptionally.
+        Layout lastKnownLayout;
+        try {
+            lastKnownLayout = layout != null ? CFUtils.getUninterruptibly(layout) : null;
+        } catch (Throwable th) {
```
Comment (corfu-repo) [inline runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java]: MAJOR Catch Exception instead of Throwable. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1181)

**Comment by corfu-repo** [comment]
SonarQube analysis reported 2 issues
* ![MAJOR][MAJOR] 2 major

Watch the comments in this conversation to review them.

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

File: test/src/test/java/org/corfudb/integration/ClusterReconfigIT.java [hunk 3]
```diff
@@ -879,4 +880,67 @@ public void healNodesWorkflowTest() throws Exception {
         shutdownCorfuServer(corfuServer_2);
         shutdownCorfuServer(corfuServer_3);
     }
+
+    /**
+     * Test that a disconnected CorfuRuntime using a systemDownHandler reconnects itself once the
+     * Server is back online.
+     */
+    @Test
+    public void reconnectDisconnectedClient() throws Exception {
```
Comment (medhavidhawan) [inline test/src/test/java/org/corfudb/integration/ClusterReconfigIT.java]: This is good. We will later need a test for the cluster as well.

File: runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java [hunk 4]
```diff
@@ -696,7 +696,17 @@ public synchronized void invalidateLayout() {
             // Don't create a new request for a layout if there is one pending.
             return;
         }
-        layout = fetchLayout(CFUtils.getUninterruptibly(layout).getLayoutServers());
+        List<String> lastKnownLayoutServers = layoutServers;
```
Comment (medhavidhawan) [inline runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java]: Let us try to clean this up in a later version. This class is very unclean and exception handling is very unwieldy.

File: test/src/test/java/org/corfudb/integration/ClusterReconfigIT.java [hunk 5]
```diff
@@ -879,4 +880,67 @@ public void healNodesWorkflowTest() throws Exception {
...
+                }
+            }
+        });
+        t.start();
+
+        assertThat(latch.tryAcquire(PARAMETERS.TIMEOUT_LONG.toMillis(), TimeUnit.MILLISECONDS))
+                .isTrue();
+        corfuServer_1 = runSinglePersistentServer(corfuSingleNodeHost, PORT_0);
+
+        t.join(PARAMETERS.TIMEOUT_LONG.toMillis());
```
Comment (annym) [inline test/src/test/java/org/corfudb/integration/ClusterReconfigIT.java]: Should you test that the client actually reconnected and that the append completed successfully? otherwise it might have timed out as well.

Comment (zalokhan) [reply test/src/test/java/org/corfudb/integration/ClusterReconfigIT.java]: @annym The append will pass only if the append was successful. Else we will not break out from the while loop.
However, I agree we need this check. I ran it locally and asserted that the append was successful. Since I have already merged this change, I will include this assertion in the PR for master rather than 0.2.1 if that's okay.

Comment (annym) [reply test/src/test/java/org/corfudb/integration/ClusterReconfigIT.java]: @zalokhan yeah that's fine with me.
