### PR TITLE
Invalidate layout on systemDownHandler.

### LINKED ISSUE #1466: Client cannot reconnect after firing systemDownHandler
## Overview

The CorfuRuntime cannot reconnect once it has invoked the systemDownHandler.
This is because the layoutCompletableFuture is stuck with the exceptionally completed layout.

Needs to be fixed in 0.2.1 and 0.2.2

### PR DESCRIPTION
**Pull request by zalokhan**
## Overview

Description:
Invalidate layout when invoking systemDownHandler. Else the layout completable future is stuck with the systemDownHandlerException forever.
Backported to 0.2.1 in #1465 

Why should this be merged: 
The layout completable future is stuck with the systemDownHandlerException forever.

Related issue(s) (if applicable): Fixes #1466 

## Checklist (Definition of Done):

- [x] There are no TODOs left in the code
- [x] [Coding conventions](https://github.com/CorfuDB/CorfuDB/wiki/Corfu-Style-Guidelines) (e.g. for logging, unit tests) have been followed
- [x] Change is covered by automated tests
- [x] Public API has Javadoc

### CODE REVIEW

**Comment by zalokhan** [comment]
@medhavidhawan @annym I have addressed your comments from #1465 here.

File: runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java [hunk 1]
```diff
@@ -701,7 +701,17 @@ public synchronized void invalidateLayout() {
             // Don't create a new request for a layout if there is one pending.
             return;
         }
-        layout = fetchLayout(CFUtils.getUninterruptibly(layout).getLayoutServers());
+        List<String> lastKnownLayoutServers = layoutServers;
```
Comment (medhavidhawan) [inline runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java]: Even though we sent it in the fix, this is not correct . The layoutServers list should come from the last know layout. Servers could have moved around but this list is static and this might not be ok.

File: runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java [hunk 2]
```diff
@@ -758,8 +768,19 @@ private void pruneRemovedRouters(@Nonnull Layout layout) {
      */
     private CompletableFuture<Layout> fetchLayout(List<String> layoutServers) {
 
+        // Layout fetch can result in an exception if the systemDownHandler was invoked and the
+        // completable future was completed exceptionally.
+        Layout lastKnownLayout;
```
Comment (medhavidhawan) [inline runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java]: there is a commonality in this code change and the code change above. Can we make one common private method.

File: runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java (hunk 1 above)
Comment (zalokhan) [reply runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java]: Done. Added a volatile global variable to record the latestLayout seen.

File: runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java (hunk 2 above)
Comment (zalokhan) [reply runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java]: Added a latestLayout to keep a record of the latest seen layout.

File: runtime/src/main/java/org/corfudb/runtime/view/AbstractView.java [hunk 3]
```diff
@@ -67,6 +67,39 @@ public Layout getCurrentLayout() {
...
+            }
+
+            if (ex.getCause() instanceof RuntimeException) {
+                log.error("getLayoutUninterruptibly: Encountered unchecked exception. "
+                        + "Aborting layoutHelper", ex);
+                throw (RuntimeException) ex.getCause();
+            }
+
+            log.error("getLayoutUninterruptibly: Encountered exception while fetching layout");
+            throw new RuntimeException(ex);
```
Comment (corfu-repo) [inline runtime/src/main/java/org/corfudb/runtime/view/AbstractView.java]: MAJOR Define and throw a dedicated exception instead of using a generic one. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS00112)

**Comment by corfu-repo** [comment]
SonarQube analysis reported 1 issue
* ![MAJOR][MAJOR] 1 major

Watch the comments in this conversation to review them.

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
