### PR TITLE
StackOverflow Fix

### LINKED ISSUE #1185: Stackoverflow Exception
## Overview

**Bug report.**

On non-transactional access a stackoverflow can happen when the object is empty/trimmed. 
We should change this to be iterative and fail after a couple of retries. 

 // Perform underlying access
        try {
            return underlyingObject.access(o -> o.getVersionUnsafe() >= timestamp
                            && !o.isOptimisticallyModifiedUnsafe(),
                    o -> o.syncObjectUnsafe(timestamp),
                    o -> accessMethod.access(o));
        } catch (TrimmedException te) {
            log.warn("Access[{}] Encountered Trim, reset and retry", this);
            // We encountered a TRIM during sync, reset the object
            underlyingObject.update(o -> {
                o.resetUnsafe();
                return null;
            });
            // And attempt an access again.
            return accessInner(accessMethod, conflictObject, isMetricsEnabled);
        }

### PR DESCRIPTION
**Pull request by Maithem**
Description:

This fix will throw a TrimmedException after a number of retries
when it non-transactionally tries to access an object, as opposed
to the previous behavior where it fails with a StackOverflowError.

Why should this be merged: 
fixes  #1185

## Checklist (Definition of Done):
- [x] There are no TODOs left in the code
- [x] [Coding conventions](https://github.com/CorfuDB/CorfuDB/wiki/Corfu-Style-Guidelines) (e.g. for logging, unit tests) have been followed
- [x] Change is covered by automated tests
- [x] Public API has Javadoc

### CODE REVIEW

File: runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java [hunk 1]
```diff
@@ -28,6 +29,7 @@
 import org.corfudb.runtime.exceptions.unrecoverable.UnrecoverableCorfuInterruptedError;
 import org.corfudb.runtime.object.transactions.AbstractTransactionalContext;
 import org.corfudb.runtime.object.transactions.TransactionalContext;
+import org.corfudb.runtime.view.Address;
```
Comment (corfu-repo) [inline runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java]: MINOR Remove this unused import 'org.corfudb.runtime.view.Address'. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AUselessImportCheck)

File: runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java [hunk 2]
```diff
@@ -17,6 +17,7 @@
 import lombok.extern.slf4j.Slf4j;
 
 import org.corfudb.protocols.logprotocol.SMREntry;
+import org.corfudb.protocols.wireprotocol.Token;
```
Comment (corfu-repo) [inline runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java]: MINOR Remove this unused import 'org.corfudb.protocols.wireprotocol.Token'. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AUselessImportCheck)

File: runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java [hunk 3]
```diff
@@ -188,29 +190,30 @@ public CorfuCompileProxy(CorfuRuntime rt, UUID streamID, Class<T> type, Object[]
...
-            underlyingObject.update(o -> {
-                o.resetUnsafe();
-                return null;
-            });
-            // And attempt an access again.
-            return accessInner(accessMethod, conflictObject, isMetricsEnabled);
+        for (int x = 0; x < rt.getParameters().getTrimRetry(); x++) {
+            // Linearize this read against a timestamp
+            final long timestamp = rt.getSequencerView()
+                            .nextToken(Collections.singleton(streamID), 0).getToken().getTokenValue();
```
Comment (corfu-repo) [inline runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java]: MINOR Remove this use of "streamID"; it is deprecated. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3ACallToDeprecatedMethod)

**Comment by corfu-repo** [comment]
SonarQube analysis reported 4 issues
* ![MAJOR][MAJOR] 1 major
* ![MINOR][MINOR] 3 minor

Watch the comments in this conversation to review them.

#### 1 extra issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [CorfuCompileProxy.java#L182](https://github.com/CorfuDB/CorfuDB/blob/4ce878364a7aed47c16a476ee7240d9dc24e5d4b/runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java#L182): Remove this unused method parameter "isMetricsEnabled". [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1172)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

File: runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java [hunk 4]
```diff
@@ -188,29 +190,30 @@ public CorfuCompileProxy(CorfuRuntime rt, UUID streamID, Class<T> type, Object[]
...
+            log.debug("Access[{}] conflictObj={} version={}", this, conflictObject, timestamp);
+
+            try {
+                return underlyingObject.access(o -> o.getVersionUnsafe() >= timestamp
+                                && !o.isOptimisticallyModifiedUnsafe(),
+                        o -> o.syncObjectUnsafe(timestamp),
+                        o -> accessMethod.access(o));
+            } catch (TrimmedException te) {
```
Comment (medhavidhawan) [inline runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java]: This needs a comment as to why trying again would fix the problem ?

File: test/src/test/java/org/corfudb/runtime/object/CompileProxyTest.java [hunk 5]
```diff
@@ -40,6 +44,30 @@ public void testObjectMapSimple() throws Exception {
                 .containsEntry("hell", "world");
     }
 
+    @Test
+    public void testTrimmedObject() throws Exception {
```
Comment (medhavidhawan) [inline test/src/test/java/org/corfudb/runtime/object/CompileProxyTest.java]: comments

File: test/src/test/java/org/corfudb/runtime/object/CompileProxyTest.java [hunk 6]
```diff
@@ -40,6 +44,30 @@ public void testObjectMapSimple() throws Exception {
...
+        // Trim all the way up to the tail
+        rt.getAddressSpaceView().prefixTrim(numOfTokens);
+        rt.getAddressSpaceView().gc();
+        rt.getAddressSpaceView().invalidateServerCaches();
+
+        Map<String, String> map = rt.getObjectsView().build()
+                .setStreamName(streamName)
+                .setTypeToken(new TypeToken<SMRMap<String,String>>() {})
+                .open();
+        assertThatThrownBy(() -> map.get("key1"))
```
Comment (medhavidhawan) [inline test/src/test/java/org/corfudb/runtime/object/CompileProxyTest.java]: what is the test trying to verify ?

File: runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java (hunk 1 above)
Comment (Maithem) [reply runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java]: done.

File: runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java (hunk 2 above)
Comment (Maithem) [reply runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java]: done.

File: runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java (hunk 4 above)
Comment (Maithem) [reply runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java]: done.

File: test/src/test/java/org/corfudb/runtime/object/CompileProxyTest.java (hunk 5 above)
Comment (Maithem) [reply test/src/test/java/org/corfudb/runtime/object/CompileProxyTest.java]: There are comments inline. 

// Advance the sequencer counter and trim up to the tail, so that the first
        // read will be on a trimmed address

File: test/src/test/java/org/corfudb/runtime/object/CompileProxyTest.java (hunk 6 above)
Comment (Maithem) [reply test/src/test/java/org/corfudb/runtime/object/CompileProxyTest.java]: added more comments.

**Comment by Maithem** [comment]
@medhavidhawan addressed comments. @no2chem please take a look.

File: runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java [hunk 7]
```diff
@@ -188,29 +186,33 @@ public CorfuCompileProxy(CorfuRuntime rt, UUID streamID, Class<T> type, Object[]
...
-                        .getTokenValue();
-        log.debug("Access[{}] conflictObj={} version={}", this, conflictObject, timestamp);
+        // try to perform the underlying access. Trim failures can happen due to fast
+        // cp/trim (i.e. after acquiring the stream tail and before the LU read a trim happens)
+        // cycles, in that case the operation is retried. The access is best effort and will
+        // give up retrying after a couple of times.
+        for (int x = 0; x < rt.getParameters().getTrimRetry(); x++) {
+            // Linearize this read against a timestamp.
+            final long timestamp = rt.getSequencerView()
+                            .nextToken(Collections.singleton(streamID), 0).getToken().getTokenValue();
```
Comment (corfu-repo) [inline runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java]: MINOR Remove this use of "streamID"; it is deprecated. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3ACallToDeprecatedMethod)

**Comment by corfu-repo** [comment]
SonarQube analysis reported 2 issues
* ![MAJOR][MAJOR] 1 major
* ![MINOR][MINOR] 1 minor

Watch the comments in this conversation to review them.

#### 1 extra issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [CorfuCompileProxy.java#L178](https://github.com/CorfuDB/CorfuDB/blob/2258175d9024531fd8185c8aae2dc164bd5c0ec8/runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java#L178): Remove this unused method parameter "isMetricsEnabled". [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1172)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

File: runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java [hunk 8]
```diff
@@ -39,22 +37,22 @@
  * In the Corfu runtime, on top of a stream,
  * an SMR object layer implements objects whose history of updates
  * are backed by a stream.
- *
+ * <p>
```
Comment (no2chem) [inline runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java]: This seems to misformat the javadoc comment needlessly?

File: runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java [hunk 9]
```diff
@@ -80,7 +78,7 @@
      */
     @Deprecated // TODO: Add replacement method that conforms to style
     @SuppressWarnings("checkstyle:abbreviation") // Due to deprecation
-    UUID streamID;
+            UUID streamID;
```
Comment (no2chem) [inline runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java]: Tabs

File: runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java [hunk 10]
```diff
@@ -188,29 +186,33 @@ public CorfuCompileProxy(CorfuRuntime rt, UUID streamID, Class<T> type, Object[]
             }
         }
 
-        // Linearize this read against a timestamp
-        final long timestamp =
-                rt.getSequencerView()
-                        .nextToken(Collections.singleton(streamID), 0).getToken()
-                        .getTokenValue();
-        log.debug("Access[{}] conflictObj={} version={}", this, conflictObject, timestamp);
+        // try to perform the underlying access. Trim failures can happen due to fast
```
Comment (no2chem) [inline runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java]: Can you leave a note that this is temporary until checkpointing is completed?

File: runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java (hunk 9 above)
Comment (Maithem) [reply runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java]: done.

File: runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java (hunk 8 above)
Comment (Maithem) [reply runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java]: hmm, intellij did that. Removed.

File: runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java (hunk 10 above)
Comment (Maithem) [reply runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java]: done.

**Comment by Maithem** [comment]
@no2chem addressed your comments.

File: runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java [hunk 11]
```diff
@@ -188,29 +186,39 @@ public CorfuCompileProxy(CorfuRuntime rt, UUID streamID, Class<T> type, Object[]
...
+         give up retrying after a couple of times.
+
+         Note: since the system should always guarantee that the latest version of the object
+         is accessible, retrying a specific number of times then giving up might not as desirable
+         as retrying until the object is accessible, but this will be addressed in checkpointing 2.0.
+         **/
+        for (int x = 0; x < rt.getParameters().getTrimRetry(); x++) {
+            // Linearize this read against a timestamp.
+            final long timestamp = rt.getSequencerView()
+                            .nextToken(Collections.singleton(streamID), 0).getToken().getTokenValue();
```
Comment (corfu-repo) [inline runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java]: MINOR Remove this use of "streamID"; it is deprecated. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3ACallToDeprecatedMethod)

**Comment by corfu-repo** [comment]
SonarQube analysis reported 2 issues
* ![MAJOR][MAJOR] 1 major
* ![MINOR][MINOR] 1 minor

Watch the comments in this conversation to review them.

#### 1 extra issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [CorfuCompileProxy.java#L178](https://github.com/CorfuDB/CorfuDB/blob/d17fac4690326f5b0c1102a101d1b6de5175be82/runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java#L178): Remove this unused method parameter "isMetricsEnabled". [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1172)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

File: runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java [hunk 12]
```diff
@@ -188,29 +186,39 @@ public CorfuCompileProxy(CorfuRuntime rt, UUID streamID, Class<T> type, Object[]
...
 
-        // Linearize this read against a timestamp
-        final long timestamp =
-                rt.getSequencerView()
-                        .nextToken(Collections.singleton(streamID), 0).getToken()
-                        .getTokenValue();
-        log.debug("Access[{}] conflictObj={} version={}", this, conflictObject, timestamp);
+        /**
+         try to perform the underlying access. Trim failures can happen due to fast
+         cp/trim (i.e. after acquiring the stream tail and before the LU read a trim happens)
```
Comment (no2chem) [inline runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java]: Don't use a javadoc style comment in line (use //)

**Comment by corfu-repo** [comment]
SonarQube analysis reported 2 issues
* ![MAJOR][MAJOR] 1 major
* ![MINOR][MINOR] 1 minor

Watch the comments in this conversation to review them.

#### 1 extra issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [CorfuCompileProxy.java#L178](https://github.com/CorfuDB/CorfuDB/blob/efe406ec3977ef8bc31fadd3de7c62f89749d1bc/runtime/src/main/java/org/corfudb/runtime/object/CorfuCompileProxy.java#L178): Remove this unused method parameter "isMetricsEnabled". [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1172)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by Maithem** [comment]
@no2chem Done.
