### PR TITLE
Transfer trimMark on stateTransfer.

### LINKED ISSUE #1395: Transfer TrimMark During State Transfer
**Bug report.**
When a node is added to the cluster through heal, or add node the trim mark is not transferred. We need to call prefix trim on that node on the current trim mark.

### PR DESCRIPTION
**Pull request by zalokhan**
## Overview

Description: Transfer the trim-mark during state transfer

Why should this be merged: The new/healed nodes will not have the trim mark. A new CorfuRuntime does not realize this and attempts to hole fill all the trimmed entries.

Related issue(s) (if applicable): Resolves #1395  

## Checklist (Definition of Done):

- [x] There are no TODOs left in the code
- [x] [Coding conventions](https://github.com/CorfuDB/CorfuDB/wiki/Corfu-Style-Guidelines) (e.g. for logging, unit tests) have been followed
- [x] Change is covered by automated tests
- [x] Public API has Javadoc

### CODE REVIEW

File: test/src/test/java/org/corfudb/integration/WorkflowIT.java [hunk 1]
```diff
@@ -304,4 +304,86 @@ public void forceRemoveTwoDeadNodes() throws Exception {
...
+        for (int i = 0; i < PARAMETERS.NUM_ITERATIONS_MODERATE; i++) {
+            if (rt.getLayoutView().getLayout().getEpoch() > layoutAfterAdds.getEpoch()) {
+                break;
+            }
+            rt.invalidateLayout();
+            Sleep.sleepUninterruptibly(PARAMETERS.TIMEOUT_SHORT);
+        }
+
+        // Assert that the new nodes should have the correct trimMark.
+        assertThat(rt.getLayoutView().getRuntimeLayout().getLogUnitClient("localhost:9001").getTrimMark().get())
```
Comment (Maithem) [inline test/src/test/java/org/corfudb/integration/WorkflowIT.java]: Also test the address space get trim mark method.

File: test/src/test/java/org/corfudb/integration/WorkflowIT.java [hunk 2]
```diff
@@ -304,4 +304,86 @@ public void forceRemoveTwoDeadNodes() throws Exception {
...
+                .isEqualTo(prefixTrimAddress + 1);
+        assertThat(rt.getLayoutView().getRuntimeLayout().getLogUnitClient("localhost:9002").getTrimMark().get())
+                .isEqualTo(prefixTrimAddress + 1);
+        FastObjectLoader fastObjectLoader = new FastObjectLoader(rt);
+        fastObjectLoader.loadMaps();
```
Comment (annym) [inline test/src/test/java/org/corfudb/integration/WorkflowIT.java]: Maybe we should call the getLogTail/getStreamsTail to verify that the FastObjectLoader properly loaded the maps?

File: test/src/test/java/org/corfudb/integration/cluster/Harness/Node.java [hunk 3]
```diff
@@ -30,6 +30,13 @@ public Node(String address, String clusterAddress, String logPath) {
         this.start = new StartAction(this);
     }
 
+    public Node(String address, String logPath) {
```
Comment (annym) [inline test/src/test/java/org/corfudb/integration/cluster/Harness/Node.java]: There is a 3 param constructor, we can call this to reduce code rep..

Comment (zalokhan) [reply test/src/test/java/org/corfudb/integration/cluster/Harness/Node.java]: Done.

File: test/src/test/java/org/corfudb/integration/WorkflowIT.java (hunk 2 above)
Comment (zalokhan) [reply test/src/test/java/org/corfudb/integration/WorkflowIT.java]: Done.

File: test/src/test/java/org/corfudb/integration/WorkflowIT.java (hunk 1 above)
Comment (zalokhan) [reply test/src/test/java/org/corfudb/integration/WorkflowIT.java]: Done.
